### ISSUE TITLE
9.0.0-SNAPSHOT having problem finding views

### ISSUE THREAD

**Issue by yogurtearl** [JakeWharton/butterknife#1061]
I have this in a lib module 
```@BindView(R2.id.foo)
   lateinit var foo: TextView

 override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
   val layout = LayoutInflater.from(context).inflate(...)     
   ButterKnife.bind(this, layout)
  }```

java.lang.IllegalStateException: Required view 'bar' with ID 213143234 for field 'foo' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.
	at butterknife.internal.Utils.findRequiredView(Utils.java:92)
	at butterknife.internal.Utils.findRequiredViewAsType(Utils.java:104)

Notice the error message mentions an unrelated view `bar`
Works with 8.5.0, but get an error with 9.0.0-20170817.220527-7

The difference seems to be related to the gen'd `_ViewBindings.java`

8.5.0 gens `target.prompt = Utils.findRequiredViewAsType(source, R.id.foo, "field 'foo'", TextView.class);`
9.0.0-SNAPSHOT gens `target.prompt = Utils.findRequiredViewAsType(source, 2131456345, "field 'foo'", TextView.class);`  

and ultimately `source.findViewById(id);` returns null (where `id` is `R2.id.foo`)
`source` contains a view with id of `R.id.foo` but not `R2.id.foo`

and then the IllegalStateException complains about an unrelated view 'bar' because `getResourceEntryName(source, id);`  returns `bar` instead of `foo`

**Comment by yogurtearl** [comment]
Might be related to https://github.com/JakeWharton/butterknife/issues/974

**Comment by JakeWharton** [comment]
Yep looks like a duplicate.
