### ISSUE TITLE
Butterknife: null views after fragment recreation on a view pager

### ISSUE THREAD

**Issue by vikas442** [JakeWharton/butterknife#1093]
Hi JakeWharton
I am using butterknife version 8.8.1. 
In my project, I have to use View Pager which will have several fragments and each fragment have its own view pager(i.e. Nested View Pager).
Now, I am facing an issue i.e. views are getting null after recreation of the fragment. 
I found a question with the same problem on [StackOverflow](https://stackoverflow.com/questions/38437735/butterknife-null-views-after-fragment-recreation-on-a-viewpager), but no solution is available there.
Here I can not set offScreenPageLimit of ViewPager to restrict the fragment recreation as there are lots of fragment and will cause the more load time for activity and also slows performance.
Any help would be highly appreciable.

**Comment by JakeWharton** [comment]
Without a sample it's impossible to know what's going on. Butter Knife just calls `findViewById` whenever you call `bind`, so it's unlikely to be a problem with the library, but rather in how you are using it.

If you can provide a failing test case or a sample that isn't a general usage problem I'd be happy to take a look. But otherwise it'd just be a guessing game.

**Comment by vikas442** [comment]
@JakeWharton I have created a sample app in which you can reproduce the issue.
Also, I have observed that this happens only if there are nested ViewPager.
Mentioned below is the link for source code:
[NestedViewPager](https://github.com/vikas442/NestedViewPager)
Steps to reproduce:

1. Go to **Fragment 3** by using next button.
2. Go back to **Fragment 1** using back button.
3. Now press back button one more time.
Application gets cash with below stacktrace:
`java.lang.NullPointerException: Attempt to invoke virtual method 'android.text.Editable android.widget.EditText.getText()' on a null object reference
                                                                              at com.daffodilsw.viewpager.ChildFragment.saveData(ChildFragment.java:73)
                                                                              at com.daffodilsw.viewpager.DemoFragmentFragment.saveDataOfCurrentPage(DemoFragmentFragment.java:114)
                                                                              at com.daffodilsw.viewpager.DemoFragmentFragment.onClick(DemoFragmentFragment.java:87)
                                                                              at com.daffodilsw.viewpager.DemoFragmentFragment_ViewBinding$1.doClick(DemoFragmentFragment_ViewBinding.java:35)
                                                                              at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                              at android.view.View.performClick(View.java:5204)
                                                                              at android.view.View$PerformClick.run(View.java:21153)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

Here on each **Back** or **Next** button click we are showing the EditText data as Toast.
At this point, it throws NPE.

Kindly look into this and let me know in case I'm doing something wrong.

**Comment by PAKalucki** [comment]
@vikas442 Could you elaborate on how you fixed the issue? I'm facing very similiar problem.

**Comment by vikas442** [comment]
@PAKalucki Initially I was using `getItem(int position)` method to get the current fragment. This gives me the issue when the page is recreated. I searched for the issue and found somewhere that we should use `instantiateItem(ViewPager pager, int position)` instead of `getItem(int position)`. `instantiateItem(ViewPager pager, int position)` method will only recreate a fragment by calling getItem(int position) if it is not created yet or it gets destroyed otherwise it will return the existing one.
Hope this will solve your problem :)

**Comment by ravithejappl** [comment]
@vikas442 Can your share your sample with solution? That would be help's more...
