### ISSUE TITLE
 Unable to find method Ljava/util/List on android studio 3.0rc2

### ISSUE THREAD

**Issue by 2665867688** [JakeWharton/butterknife#1116]
Error:Unable to find method 'com.android.build.gradle.api.BaseVariant.getOutputs()Ljava/util/List;'.
butterknife Caused by: java.lang.NoSuchMethodError: com.android.build.gradle.api.BaseVariant.getOutputs()Ljava/util/List;
	at butterknife.plugin.ButterKnifePlugin$applyPlugin$1.execute(ButterKnifePlugin.kt:27)
	at butterknife.plugin.ButterKnifePlugin$applyPlugin$1.execute(ButterKnifePlugin.kt:15)

on Android studio 3.0rc2

**Comment by JakeWharton** [comment]
You have to use 9.0.0-SNAPSHOT for AGP 3.0 support.
