### ISSUE TITLE
NoSuchMethodError: com.android.build.gradle.tasks.ProcessAndroidResources.getPackageForR()Ljava/lang/String;

### ISSUE THREAD

**Issue by scottkennedy** [JakeWharton/butterknife#1124]
```
Caused by: java.lang.NoSuchMethodError: com.android.build.gradle.tasks.ProcessAndroidResources.getPackageForR()Ljava/lang/String;
        at butterknife.plugin.ButterKnifePlugin$configureR2Generation$1$1.execute(ButterKnifePlugin.kt:59)
        at butterknife.plugin.ButterKnifePlugin$configureR2Generation$1$1.execute(ButterKnifePlugin.kt:18)
```

It seems that AGP 3.1 has removed a method that the plugin uses.

**Comment by JakeWharton** [comment]
Can use `getOriginalApplicationId` but it'll also break eventually.

**Comment by amrfarid140** [comment]
I am facing the same error. How can I workaround it?

**Comment by JakeWharton** [comment]
Use 3.0.0

**Comment by amrfarid140** [comment]
Sorry but 3.0.0 of what, Android Studio?

**Comment by JakeWharton** [comment]
Android Gradle plugin

**Comment by dazza5000** [comment]
Thank you

**Comment by kassim** [comment]
I'm getting this stack trace on building after updating to `com.android.tools.build:gradle:3.1.0-alpha05`


```
java.lang.NoSuchMethodError: com.android.build.gradle.tasks.ProcessAndroidResources.getOriginalApplicationId()Ljava/lang/String;
        at butterknife.plugin.ButterKnifePlugin$configureR2Generation$1$1.execute(ButterKnifePlugin.kt:59)
        at butterknife.plugin.ButterKnifePlugin$configureR2Generation$1$1.execute(ButterKnifePlugin.kt:18)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:136)
        at butterknife.plugin.ButterKnifePlugin$configureR2Generation$1.execute(ButterKnifePlugin.kt:52)
        at butterknife.plugin.ButterKnifePlugin$configureR2Generation$1.execute(ButterKnifePlugin.kt:18)
        at org.gradle.internal.ImmutableActionSet$CompositeSet.execute(ImmutableActionSet.java:196)
        at org.gradle.internal.MutableActionSet.execute(MutableActionSet.java:35)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:204)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:198)
        at com.android.build.gradle.LibraryExtension.addVariant(LibraryExtension.java:90)
        at com.android.build.gradle.internal.ApiObjectFactory.create(ApiObjectFactory.java:132)
        at com.android.build.gradle.BasePlugin.lambda$createAndroidTasks$6(BasePlugin.java:700)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:686)
        at com.android.build.gradle.BasePlugin.lambda$null$4(BasePlugin.java:604)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
        at com.android.build.gradle.BasePlugin.lambda$createTasks$5(BasePlugin.java:600)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
```
