### ISSUE TITLE
Quoting Butter Knife 8.8.1 in the library, using BindView in the app module, but the view appears NullPointerException

### ISSUE THREAD

**Issue by qinxianyuzou** [JakeWharton/butterknife#1127]
I used a butterknife 8.8.1 in AndroidStudio3.0。
My project gradle：
```
buildscript {
    repositories {
        jcenter()
        ......
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'
        classpath 'com.jakewharton:butterknife-gradle-plugin:9.0.0-SNAPSHOT'
    }
}
allprojects {
    repositories {
        jcenter()
        ......
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
        google()
    }
}
```
In my app module gradle:
```
......
apply plugin: 'com.jakewharton.butterknife'
```
In my Library module gradle:
```
apply plugin: 'com.android.library'
dependencies {
    ......
    compile "com.jakewharton:butterknife:${butterknifeSdkVersion}"
    annotationProcessor "com.jakewharton:butterknife-compiler:${butterknifeSdkVersion}"
}
```
In my app module activity binding View, @ BindView (R.id.xx) and @BindView (R2.id.xx) have tried, but still NullPointerException.Why is that？

--------------------------------------------------
My English is relatively poor, the above text from the Google translation, grammar unreasonable please understand

**Comment by JakeWharton** [comment]
Turn on debug logging on the `ButterKnife` object. What logs are printed? Can you see the generated code in your `build/generated/source/` folder? In the APK?

**Comment by qinxianyuzou** [comment]
Thanks @JakeWharton reply.
I open the butter knife debug, run the app, the logcat shows the following log:
```
......
D/ButterKnife: Looking up binding for com......activity.MainActivity
D/ButterKnife: Not found. Trying superclass com......BaseActivity
D/ButterKnife: Not found. Trying superclass android.support.v7.app.AppCompatActivity
D/ButterKnife: MISS: Reached framework class. Abandoning search.
......
```
My app module in `build/generated/source/` not ViewBinder file
> Turn on debug logging on the ButterKnife object. What logs are printed? Can you see the generated code in your build/generated/source/ folder? In the APK?

**Comment by imaiya** [comment]
I encountered the same problem,user gradle:3.0.0 and butterknife 8.8.1;

- ButterKnife.bind(this) in library, 
- @BindView(R.id.xx) in app,
exception :NullPointerException

**Comment by qinxianyuzou** [comment]
@imaiya 并没有，其实有个简单的解决办法，直接把butterknife挂在app module里面，而不在library里挂，这样就不会出现问题，不过这么搞不符合组件开发而已。不仅仅是在studio3.0，在2.3的时候用butterknife挂在library里也是会这样的，所以我不懂是不是配置没有配置正确还是butterknife有bug
> I encountered the same problem,user gradle:3.0.0 and butterknife 8.8.1;
ButterKnife.bind(this) in library,
@bindview(R.id.xx) in app,
exception :NullPointerException
@qinxianyuzou 兄弟你这个问题解决了吗,我升级到3.0遇到这个问题,很烦

**Comment by imaiya** [comment]
@qinxianyuzou 对啊,我这边是有基础library,在library的基类中bind(this),在app具体页面中使用bindview,之前使用7.x是没有问题的,但是因为升级3.0需要使用8.x,升级之后就报空了;如果单独拎出来会破坏基础库的机构,不是很想这样做,如果找到好的解决方案callback一下哈

**Comment by qinxianyuzou** [comment]
我的项目更加复杂，项目架构是主管架构的，弄得特别复杂，一个基础library库，然后一个基类library库，最后才是app的一层依赖一层，我不知道是不是这个原因导致了butterknife失效了，如果是，那就麻烦了，他自己不升级studio，然后我就要降回2.3去开发各种......
> @qinxianyuzou 对啊,我这边是有基础library,在library的基类中bind(this),在app具体页面中使用bindview,之前使用7.x是没有问题的,但是因为升级3.0需要使用8.x,升级之后就报空了;如果单独拎出来会破坏基础库的机构,不是很想这样做,如果找到好的解决方案callback一下哈

**Comment by ranjitzade** [comment]
@JakeWharton  I am getting the same error in android studio 3.0.0 and butterknife 8.8.1

**Comment by wvisible** [comment]
@qinxianyuzou @imaiya Try adding 'annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'' to the module

**Comment by qinxianyuzou** [comment]
@wvisible Is it added in the app module and not in the library?

**Comment by wvisible** [comment]
@qinxianyuzou yes,you can try it.

**Comment by imaiya** [comment]
@wvisible @qinxianyuzou Thank you for the suggestion that I used this method to solve the problem

**Comment by qinxianyuzou** [comment]
@wvisible You're right, this method can solve the problem, but doing so is tantamount to direct the butter knife on the app module Nothing to do with the library, which is not in line with the idea I put the butter knife into the Library.I hope that the library is perfect and independent, not every time need to add in the app module

**Comment by wangyuetingtao** [comment]
在defaultConfig中加入
javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath true
            }
        }
就可以继续用7.0.1啦，当前最新版本的问题还请 @JakeWharton 大神解决下

**Comment by wimvogt** [comment]
you can add
```
dependencies {
    ......
    compile "com.jakewharton:butterknife:${butterknifeSdkVersion}"
    annotationProcessor "com.jakewharton:butterknife-compiler:${butterknifeSdkVersion}"
}
```
in  app module build.gradle also

**Comment by qinxianyuzou** [comment]
@wimvogt Yes, I know this, but it does not solve the problem of using a butterknife in a library.

> you can add
> 
> dependencies {
>     ......
>     compile "com.jakewharton:butterknife:${butterknifeSdkVersion}"
>     annotationProcessor "com.jakewharton:butterknife-compiler:${butterknifeSdkVersion}"
> }
> in app module build.gradle too.

**Comment by Drakot** [comment]
I deleted **_apply plugin: 'com.jakewharton.butterknife'_** and It worked

**Comment by nirmal912** [comment]
did anyone find a solution? I am facing the same problem in gradle:3.0.0

**Comment by fauzanmakky** [comment]
use gradle:3.0.0 and butterknife 8.8.1;
when i open my apps, my apps running well, but when i accses view to often in some frgament (replace fragment) in short time, the view being null.
@JakeWharton

**Comment by BansookNam** [comment]
I had no problem after change to Android Studio 3.0,
gradle 3.0.0, with butterknife 8.8.1
I'm using butterknife in app module. (not library)

However after change part of code kotlin.
the problem happened in a same way.

Build has no problem but after run the app.
all views with @BindView is null. 
of course I called Butterknife.bind(). however it dosen't work.
(Ps. the problem happened with using @BindView in a .java file)

need a help.

**Comment by kassim** [comment]
@BansookNam are you using `kapt` instead of `annotationProcessor` for your Butterknife dependency statement in your `build.gradle`?

I had the same issue when introducing Kotlin

**Comment by BansookNam** [comment]
@kassim Thank you kassim
I just used "kapt" a minute ago and solved the problem.
have a good day~!

**Comment by relish-wang** [comment]
Android Studio 3.0, library module, no kotlin.
It works for me:
```
dependencies {
    // butterknife
    compile 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife:8.8.1' // add this 
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
}
```

**Comment by shenwenbin123** [comment]
@qinxianyuzou I have the same problem. I don't know if you've solved the problem now

**Comment by qinxianyuzou** [comment]
@shenwenbin123 No, at the moment I can only solve the problem by loading butterknife into the application module.

**Comment by shaojin8864** [comment]
@qinxianyuzou  你好，我碰到的问题和这个不太一样，我在testApp中引用了chatlib这个库，在chatlib这个库中使用了butterknife9.0.0-SNAPSHOT，然后我的chatlib这个library库还依赖了baselib这个库。我在chatlib中使用R2.id.content引用这个资源，在testApp中调用它就出现异常了。

> 12-07 15:29:36.309 3201-4335/? E/MultiWinService: releaseMultiWin: invalid parameter, Token{28be7bd2 ActivityRecord{2851c834 u0 com.example.saitron/.MainActivity t26}}
12-07 15:29:36.309 3201-4335/? E/MultiWinService: releaseMultiWin: invalid parameter, Token{28be7bd2 ActivityRecord{2851c834 u0 com.example.saitron/.MainActivity t26}}
12-07 15:30:51.989 31726-31726/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example.saitron, PID: 31726
                                                   java.lang.NoSuchFieldError: No static field fragment_content of type I in class Lcom/lib/saitronlib/R$id; or its superclasses (declaration of 'com.lib.saitronlib.R$id' appears in /data/app/com.example.saitron-2/split_lib_slice_5_apk.apk)
                                                       at com.hbsc.oaphone.commonmodule.activity.MainTabActivity_ViewBinding.<init>(MainTabActivity_ViewBinding.java:35)
                                                       at java.lang.reflect.Constructor.newInstance(Native Method)
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                       at butterknife.ButterKnife.createBinding(ButterKnife.java:198)
                                                       at butterknife.ButterKnife.bind(ButterKnife.java:123)
                                                       at com.hbsc.oaphone.commonmodule.activity.MainTabActivity.createViews(MainTabActivity.java:139)
                                                       at com.hbsc.base.BaseActivity.onCreate(BaseActivity.java:52)
                                                       at android.app.Activity.performCreate(Activity.java:6100)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2407)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2516)
                                                       at android.app.ActivityThread.access$1200(ActivityThread.java:163)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1374)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5601)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
12-07 15:30:52.039 4781-4948/? E/SubmitMessage: Submit string: submit:trigger=0,bugtype=2,modulename=com.example.saitron,level=1,testtype=NORMAL,path=/data/log/unzip/M2-A01W_V100R001C233B023_0000000000_20161207153052_crash,mode=1
12-07 15:32:09.569 3201-4336/? E/MultiWinService: releaseMultiWin: invalid parameter, Token{1472c26a ActivityRecord{958170c u0 com.example.saitron/.MainActivity t27}}
12-07 15:32:09.569 3201-4336/? E/MultiWinService: releaseMultiWin: invalid parameter, Token{1472c26a ActivityRecord{958170c u0 com.example.saitron/.MainActivity t27}}
```public class MainTabActivity_ViewBinding implements Unbinder {
  private MainTabActivity target;

  private View view2131493484;

  private View view2131493095;

  @UiThread
  public MainTabActivity_ViewBinding(MainTabActivity target) {
    this(target, target.getWindow().getDecorView());
  }

  @UiThread
  public MainTabActivity_ViewBinding(final MainTabActivity target, View source) {
    this.target = target;
   //我发现这里在获取的时候使用R.id.fragment_content是得不到这个field的，
  //使用R2.id.fragment_content也得不到。
    View view;
    target.fragmentContent = Utils.findRequiredViewAsType(source, R.id.fragment_content, "field 'fragmentContent'", FrameLayout.class);
    target.mainRadiogroup = Utils.findRequiredViewAsType(source, R.id.main_radiogroup, "field 'mainRadiogroup'", RadioGroup.class);
    view = Utils.findRequiredView(source, R.id.topimg, "field 'topimg' and method 'on_click'");
    target.topimg = Utils.castView(view, R.id.topimg, "field 'topimg'", ImageView.class);
    view2131493484 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.on_click(p0);
      }
    });
    target.ivActionbarLeft = Utils.findRequiredViewAsType(source, R.id.iv_actionbar_left, "field 'ivActionbarLeft'", ImageView.class);
    target.tabRboLatestMessage = Utils.findRequiredViewAsType(source, R.id.tab_rbo_latest_message, "field 'tabRboLatestMessage'", RadioButton.class);
    target.tabRboTongxunlu = Utils.findRequiredViewAsType(source, R.id.tab_rbo_tongxunlu, "field 'tabRboTongxunlu'", RadioButton.class);
    target.tabRboMe = Utils.findRequiredViewAsType(source, R.id.tab_rbo_me, "field 'tabRboMe'", RadioButton.class);
    view = Utils.findRequiredView(source, R.id.imageView_actionbar_search, "field 'imageViewActionbarSearch' and method 'on_click'");
    target.imageViewActionbarSearch = Utils.castView(view, R.id.imageView_actionbar_search, "field 'imageViewActionbarSearch'", ImageView.class);
    view2131493095 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.on_click(p0);
      }
    });
  }`
这是我chatlib的build.gradle文件

> apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife'
apply plugin: 'org.greenrobot.greendao'
android {
    compileSdkVersion 25
    buildToolsVersion '26.0.2'
    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        javaCompileOptions { annotationProcessorOptions { includeCompileClasspath = true } }
    }
    testOptions {
        unitTests.returnDefaultValues = true
    }
    sourceSets {
        main {
            java.srcDirs = ['src/main/java', 'src/main/aidl']
        }
    }
    useLibrary 'org.apache.http.legacy'
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
            jniDebuggable true
            renderscriptDebuggable true
        }
    }
    lintOptions {
        disable 'MissingTranslation'
    }
    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    productFlavors {
    }
}
greendao {
    schemaVersion 9
}
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    //http请求测试框架
    //测试框架
    implementation files('libs/log4j-1.2.17.jar')
    implementation files('libs/mina-core-2.0.15.jar')
    implementation files('libs/okhttp-2.5.0.jar')
    implementation files('libs/okio-1.4.0.jar')
    implementation files('libs/otto-1.3.8.jar')
    implementation files('libs/picasso-2.5.2.jar')
    implementation files('libs/slf4j-api-1.7.5.jar')
    implementation files('libs/slf4j-nop-1.7.5.jar')
    implementation files('libs/android-logging-log4j-1.0.3.jar')
    implementation files('libs/sangforSDK.jar')
    implementation files('libs/HwPush_SDK_V2705.jar')
    implementation files('libs/MiPush_SDK_Client_3_4_5.jar')
    implementation 'com.jakewharton:butterknife:9.0.0-SNAPSHOT'
    annotationProcessor 'com.jakewharton:butterknife-compiler:9.0.0-SNAPSHOT'
    implementation 'com.android.support:multidex:1.0.2'
    //greendao数据库框架
    implementation 'com.github.hotchemi:permissionsdispatcher:2.1.3'
    implementation 'com.android.support:appcompat-v7:25.4.0'
    implementation 'com.nineoldandroids:library:2.4.0'
    implementation 'com.google.code.gson:gson:2.8.0'
    implementation 'com.tencent.bugly:crashreport:2.6.6.1'
    implementation 'com.github.bumptech.glide:glide:3.7.0'
    implementation 'com.android.support:recyclerview-v7:25.4.0'
    implementation 'com.android.support:design:25.4.0'
    implementation 'org.greenrobot:greendao:3.1.0'
    implementation 'com.orhanobut:logger:2.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    testImplementation 'com.squareup.okhttp3:mockwebserver:3.8.0'
    testImplementation 'org.mockito:mockito-core:1.10.19'
    testImplementation 'org.robolectric:robolectric:3.3.2'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    annotationProcessor 'com.github.hotchemi:permissionsdispatcher-processor:2.1.3'
    implementation 'com.jakewharton.rxbinding2:rxbinding:2.0.0'
    implementation 'com.andkulikov:transitionseverywhere:1.7.6'
    implementation 'com.android.support:palette-v7:25.4.0'
    compile project(':saitronLib')
}

configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '25.4.0'
            }
        }
    }
}

**Comment by wangkunlin** [comment]
@qinxianyuzou 这个不是 bug ，因为 butterknife 的工作机制是：利用 annotationProcessor 来生成 XXX_ViewBinding 类的，对应的 XXX 里面的 View 的初始化是在 XXX_ViewBinding 内完成的。
而 annotationProcessor 是以 module 为单位工作的，所以解决方法很简单，在 app module 内引用 annotationProcessor 而在 library 内引用 butterknife 即可解决。
@imaiya  在基类里 bind 我不认为能行，即使使用我上面说的方法，为什么呢？看代码
```java

  @Nullable @CheckResult @UiThread
  private static Constructor<? extends Unbinder> findBindingConstructorForClass(Class<?> cls) {
    Constructor<? extends Unbinder> bindingCtor = BINDINGS.get(cls);
    if (bindingCtor != null) {
      if (debug) Log.d(TAG, "HIT: Cached in binding map.");
      return bindingCtor;
    }
    String clsName = cls.getName();
    if (clsName.startsWith("android.") || clsName.startsWith("java.")) {
      if (debug) Log.d(TAG, "MISS: Reached framework class. Abandoning search.");
      return null;
    }
    try {
      Class<?> bindingClass = Class.forName(clsName + "_ViewBinding");
      //noinspection unchecked
      bindingCtor = (Constructor<? extends Unbinder>) bindingClass.getConstructor(cls, View.class);
      if (debug) Log.d(TAG, "HIT: Loaded binding class and constructor.");
    } catch (ClassNotFoundException e) {
      // 这里是想上找父类，而不会向下找子类
      if (debug) Log.d(TAG, "Not found. Trying superclass " + cls.getSuperclass().getName());
      bindingCtor = findBindingConstructorForClass(cls.getSuperclass());
    } catch (NoSuchMethodException e) {
      throw new RuntimeException("Unable to find binding constructor for " + clsName, e);
    }
    BINDINGS.put(cls, bindingCtor);
    return bindingCtor;
  }
```
个人见解，轻喷

**Comment by luckbing** [comment]
@qinxianyuzou 大神，问题解决没？我无意间看到其他大神在library里面引用butterknife，首先在project的gradle文件里面的buildscript下面用butterknife作者提供的插件dependencies {
    classpath 'com.jakewharton:butterknife-gradle-plugin:8.8.1'
  }，然后在library的module的gradle里面添加上这两个插件：
apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife'
，最后在所有@BindView的地方用R2.id.***替换掉R.id.***,这样就不会空指针了，好像butterknife的readme里面也是这样介绍的，可能大神你没太注意，希望可以帮助到你和其他遇到问题的大神们，好像说是android资源查找的机制导致的，所以jakewharton大神自己提供了一个gradle插件com.jakewharton:butterknife-gradle-plugin:***就是解决这个问题的

**Comment by gmm932** [comment]
must add  `annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'` in app module to solve this problem.

**Comment by gitaarush** [comment]
Thank you @gmm932  Your suggestion works (probably  missed that part from README file)

**App level configuration:**
```
dependencies {
    implementation 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
}

```
**Project level configuration:**
```
buildscript {
     dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        **classpath 'com.jakewharton:butterknife-gradle-plugin:8.8.1'**
  }
}
```

**Comment by kaxi4it** [comment]
@qinxianyuzou 最后有搞定吗？在lib中引入黄油刀，在app module中使用
我是as 3.0.1 gradle 3.0.1

**Comment by cjiahuan** [comment]
My App also had this problem, this was because I used Glide 4.0 in my app. I could not find viewbinging.class from build/generated/source. For updaeing Glide to 4.0 version, I add code: `kapt 'com.github.bumptech.glide:compiler:4.7.1'`.  Then butterknife 7.0 did not work!!! So, I updated butterknife to  8.0+, also no work!! But, when I changed code `annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'` to `kapt 'com.jakewharton:butterknife-compiler:8.8.1'`, it worked.

**Comment by ximencx** [comment]
同样的问题 gradle4.1  tools:3.1.0,  跑不起来

**Comment by ximencx** [comment]
有解决的么  lib的build放入依赖 ，，app放注解，也报错

**Comment by wangkunlin** [comment]
按着 README.md 里的方法配置就可以了。

**Comment by ximencx** [comment]
@wangkunlin 最后default加了一段代码  还用7.0.1解决，这个框架不建议在项目中用，不如base里抽个findview'byid兼容性好
