### ISSUE TITLE
 java.lang.NoSuchMethodError in Android Studio3.0

### ISSUE THREAD

**Issue by zf530820145** [JakeWharton/butterknife#1129]
i have some question. Yesterday my project was running normally,but today my project have some problem.Throw ```java.lang.NoSuchMethodError```.I fixed it when i use this method.
` compile('com.jakewharton:butterknife:9.0.0-SNAPSHOT') {
        exclude module: 'appcompat-v7'
        exclude group: 'com.android.support'
    }`.What's probleam?

**Comment by JakeWharton** [comment]
You haven't provided enough information to diagnose a problem. How about a full stacktrace to start.

**Comment by zf530820145** [comment]
this is the full stacktrace:

```
java.lang.NoSuchMethodError: No static method getFont(Landroid/content/Context;ILandroid/util/TypedValue;ILandroid/widget/TextView;)Landroid/graphics/Typeface; in class Landroid/support/v4/content/res/ResourcesCompat; or its super classes (declaration of 'android.support.v4.content.res.ResourcesCompat' appears in /data/app/com.globalegrow.app.gearbest-1/base.apk:classes28.dex)
W:     at android.support.v7.widget.TintTypedArray.getFont(TintTypedArray.java:119)
W:     at android.support.v7.widget.AppCompatTextHelper.updateTypefaceAndStyle(AppCompatTextHelper.java:208)
W:     at android.support.v7.widget.AppCompatTextHelper.loadFromAttributes(AppCompatTextHelper.java:110)
W:     at android.support.v7.widget.AppCompatTextHelperV17.loadFromAttributes(AppCompatTextHelperV17.java:38)
W:     at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:81)
W:     at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:71)
W:     at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
W:     at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1024)
W:     at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1081)
W:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
W:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
W:     at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
W:     at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
W:     at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
```

i fixed this error  by add this
 ``` { exclude module: 'appcompat-v7' exclude group: 'com.android.support' }``` in build.gradle,
but i dont know why? Can u explain it?

**Comment by JakeWharton** [comment]
Don't do that. You should depend on version 27.0.0 of the support libraries to use the latest version of Butter Knife.
