### ISSUE TITLE
java.lang.IllegalStateException: Required view 'recyclerView_gateway_list' with ID 2131821197 for field 'recyclerView_gateway_list' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.

### ISSUE THREAD

**Issue by skbhati199** [JakeWharton/butterknife#1138]
```
java.lang.IllegalStateException: Required view 'recyclerView_gateway_list' with ID 2131821197 for field 'recyclerView_gateway_list' was not found. If this view is optional add 
'@Nullable' (fields) or '@Optional' (methods) annotation.
                                                                                     
   at butterknife.internal.Finder.findRequiredView(Finder.java:71)
                                                                                        at butterknife.internal.Finder.findRequiredViewAsType(Finder.java:82)
                                                                                        at com.metroinfrasys.highwaysaathi.PaymentListWallets$$ViewBinder$InnerUnbinder.<init>(PaymentListWallets$$ViewBinder.java:25)
                                                                                        at com.metroinfrasys.highwaysaathi.PaymentListWallets$$ViewBinder.bind(PaymentListWallets$$ViewBinder.java:16)
                                                                                        at com.metroinfrasys.highwaysaathi.PaymentListWallets$$ViewBinder.bind(PaymentListWallets$$ViewBinder.java:13)
                                                                                        at butterknife.ButterKnife.bind(ButterKnife.java:167)
                                                                                        at com.metroinfrasys.highwaysaathi.Adapter.PassTagGatewayListAdapter$ViewHolder.<init>(PassTagGatewayListAdapter.java:91)
                                                                                        at com.metroinfrasys.highwaysaathi.Adapter.PassTagGatewayListAdapter.onCreateViewHolder(PassTagGatewayListAdapter.java:44)
                                                                                        at com.metroinfrasys.highwaysaathi.Adapter.PassTagGatewayListAdapter.onCreateViewHolder(PassTagGatewayListAdapter.java:29)
                                                                                        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6411)
                                                                                        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5597)
                                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5482)
                                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5478)
                                                                                        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2215)
                                                                                        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1542)
                                                                                        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1502)
                                                                                        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                                        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3625)
                                                                                        at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3067)
                                                                                        at android.view.View.measure(View.java:19756)
                                                                                        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                                        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                                        at android.view.View.measure(View.java:19756)
                                                                                        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                                        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                                        at android.view.View.measure(View.java:19756)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
                                                                                        at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:713)
                                                                                        at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:90)
                                                                                        at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1389)
                                                                                        at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:783)
                                                                                        at android.view.View.measure(View.java:19756)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
                                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                                        at android.view.View.measure(View.java:19756)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
                                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                                        at android.view.View.measure(View.java:19756)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
                                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                        at android.view.View.measure(View.java:19756)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
                                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
11-06 15:17:34.672 19385-19385/com.metroinfrasys.highwaysaathi E/UncaughtException:     


at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                                        at android.view.View.measure(View.java:19756)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
                                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:687)
                                                                                        at android.view.View.measure(View.java:19756)
                                                                                        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2283)
                                                                                        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1370)
                                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
                                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1258)
                                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6348)
                                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                                        at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

```
    apt 'com.jakewharton:butterknife-compiler:8.1.0'
````

**Comment by skbhati199** [comment]
``````

   ButterKnife.bind(this, view);  fix bug 



```

I'm passing wrong context in view
