### ISSUE TITLE
How to solved this problem : java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1646740 bytes

### ISSUE THREAD

**Issue by Prabha10cs** [JakeWharton/butterknife#1142]
FATAL EXCEPTION: main
                                                   Process: com.appname, PID: 15550
                                                   java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1646740 bytes
                                                       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3781)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                    Caused by: android.os.TransactionTooLargeException: data parcel size 1646740 bytes
                                                       at android.os.BinderProxy.transactNative(Native Method)
                                                       at android.os.BinderProxy.transact(Binder.java:615)
                                                       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3636)
                                                       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3773)
                                                       at android.os.Handler.handleCallback(Handler.java:751) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by JakeWharton** [comment]
This is not related to Butter Knife.

**Comment by hardy-android** [comment]
This issue occurs android version >=Naugat
More info Refer: https://stackoverflow.com/questions/11451393/what-to-do-on-transactiontoolargeexception

**Comment by Thakkar1234** [comment]
If you are passing too much data using intent then this kind of error is occurred.
1.) Make sure you are finishing previous activity while start another activity.
2.) If possible use POJO class to transfer data instead of directly using key and value.

**Comment by byencho** [comment]
The more relevant discussion for this issue is [here](https://stackoverflow.com/a/44738411/5635880). I'd recommend taking look into [Bridge](https://github.com/livefront/bridge) for a solution if you are still seeing the problem.

**Comment by WaiYan98** [comment]
> If you are passing too much data using intent then this kind of error is occurred.
> 1.) Make sure you are finishing previous activity while start another activity.
> 2.) If possible use POJO class to transfer data instead of directly using key and value.

Thanks

**Comment by WaiYan98** [comment]
> > If you are passing too much data using intent then this kind of error is occurred.
> > 1.) Make sure you are finishing previous activity while start another activity.
> > 2.) If possible use POJO class to transfer data instead of directly using key and value.
> 
> Thanks! It really work for me.
