### ISSUE TITLE
Binding onClick for Multiple Button 

### ISSUE THREAD

**Issue by azzahrah** [JakeWharton/butterknife#1192]
How to implementation binding onclick event for multiple button like this

 @Override
   public void onClick(View view){
     switch(view.getId()){
       case R.id.btn_submit:
       break;
      case R.id.btn_cancel:
       break;
    }
}

**Comment by JeckChou** [comment]
```
@Onclick({R.id.a,R.id.b,R.id.c})
void onButtonClick(View aView) {
//you code here
}
```

**Comment by azzahrah** [comment]
I get error:


`01-29 05:21:19.913 3831-3831/com.centratelemedia.gpstracker E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NullPointerException
        at android.view.GLES20Canvas.setupModifiers(GLES20Canvas.java:1365)
        at android.view.GLES20Canvas.drawLines(GLES20Canvas.java:946)
        at android.view.GLES20RecordingCanvas.drawLines(GLES20RecordingCanvas.java:161)
        at android.view.GLES20Canvas.drawLine(GLES20Canvas.java:936)
        at android.view.GLES20RecordingCanvas.drawLine(GLES20RecordingCanvas.java:155)
        at android.graphics.drawable.GradientDrawable.draw(GradientDrawable.java:537)
        at android.graphics.drawable.DrawableContainer.draw(DrawableContainer.java:66)
        at android.view.View.draw(View.java:13929)
        at android.view.View.getDisplayList(View.java:12838)
        at android.view.View.getDisplayList(View.java:12880)
        at android.view.View.draw(View.java:13657)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3086)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2923)
        at android.view.View.draw(View.java:13947)
        at android.widget.FrameLayout.draw(FrameLayout.java:467)
        at android.view.View.getDisplayList(View.java:12838)
        at android.view.View.getDisplayList(View.java:12880)
        at android.view.View.draw(View.java:13657)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3086)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2923)
        at android.view.View.getDisplayList(View.java:12833)
        at android.view.View.getDisplayList(View.java:12880)
        at android.view.View.draw(View.java:13657)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3086)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2923)
        at android.view.View.getDisplayList(View.java:12833)
        at android.view.View.getDisplayList(View.java:12880)
        at android.view.View.draw(View.java:13657)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3086)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2923)
        at android.view.View.getDisplayList(View.java:12833)
        at android.view.View.getDisplayList(View.java:12880)
        at android.view.View.draw(View.java:13657)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3086)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2923)
        at android.view.View.draw(View.java:13947)
        at android.widget.FrameLayout.draw(FrameLayout.java:467)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2224)
        at android.view.View.getDisplayList(View.java:12838)
        at android.view.View.getDisplayList(View.java:12880)
        at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1411)
        at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1359)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2367)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2239)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1872)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5481)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
        at android.view.Choreographer.doCallbacks(Choreographer.java:562)
        at android.view.Choreographer.doFrame(Choreographer.java:532)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
        at android.os.Handler.handleCallback(Handler.java:730)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5103)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)`

**Comment by JakeWharton** [comment]
That is not caused by this library.
