### ISSUE TITLE
robolectric 3.8 +butterknife 8.4.0,ClassCastException

### ISSUE THREAD

**Issue by chenxihoulang** [JakeWharton/butterknife#1279]
java.lang.IllegalStateException: View 'titleBar' with ID 2131296853 for field 'titleBar' was of the wrong type. See cause for more info.
	at butterknife.internal.Utils.castView(Utils.java:113)
	at butterknife.internal.Utils.findRequiredViewAsType(Utils.java:105)
	at com.baby.android.phone.principal.JunitActivity_ViewBinding.<init>(JunitActivity_ViewBinding.java:21)
	at butterknife.ButterKnife.createBinding(ButterKnife.java:199)
	at butterknife.ButterKnife.bind(ButterKnife.java:124)
	at com.baby.android.common.activities.BaseActivity.onCreate(BaseActivity.java:45)
	at com.baby.commonlibrary.base.activity.BaseHbbActivity.onCreate(BaseHbbActivity.java:33)
	at android.app.Activity.performCreate(Activity.java:6251)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:249)
	at org.robolectric.android.controller.ActivityController$1.run(ActivityController.java:62)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:359)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:59)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:69)
	at org.robolectric.android.controller.ActivityController.setup(ActivityController.java:176)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:88)
	at com.baby.android.phone.principal.JunitActivityTest.onLayoutInflater(JunitActivityTest.java:17)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:570)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.powermock.modules.junit4.rule.PowerMockStatement$1.run(PowerMockRule.java:65)
	at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:1873)
	at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:773)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:638)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:401)
	at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:98)
	at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:78)
	at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:57)
	at com.cmcc.hbb.android.phone.principal.LogRule.apply(LogRule.java:21)
	at org.junit.rules.RunRules.applyAll(RunRules.java:26)
	at org.junit.rules.RunRules.<init>(RunRules.java:15)
	at org.junit.runners.BlockJUnit4ClassRunner.withTestRules(BlockJUnit4ClassRunner.java:400)
	at org.junit.runners.BlockJUnit4ClassRunner.withRules(BlockJUnit4ClassRunner.java:356)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:278)
	at org.robolectric.internal.SandboxTestRunner$HelperTestRunner.methodBlock(SandboxTestRunner.java:312)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:249)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassCastException: Cannot cast com.baby.phone.widget.ColorTitleBar to com.baby.phone.widget.ColorTitleBar
	at java.lang.Class.cast(Class.java:3369)
	at butterknife.internal.Utils.castView(Utils.java:110)
	at butterknife.internal.Utils.findRequiredViewAsType(Utils.java:105)
	at com.baby.android.phone.principal.JunitActivity_ViewBinding.<init>(JunitActivity_ViewBinding.java:21)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at butterknife.ButterKnife.createBinding(ButterKnife.java:199)
	at butterknife.ButterKnife.bind(ButterKnife.java:124)
	at com.baby.android.common.activities.BaseActivity.onCreate(BaseActivity.java:45)
	at com.baby.phone.commonlibrary.base.activity.BaseHbbActivity.onCreate(BaseHbbActivity.java:33)
	at android.app.Activity.$$robo$$performCreate(Activity.java:6251)
	at android.app.Activity.performCreate(Activity.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:249)
	at org.robolectric.android.controller.ActivityController$1.run(ActivityController.java:62)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:359)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:59)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:69)
	at org.robolectric.android.controller.ActivityController.setup(ActivityController.java:176)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:88)
	at com.baby.android.phone.principal.JunitActivityTest.onLayoutInflater(JunitActivityTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:570)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.powermock.modules.junit4.rule.PowerMockStatement$1.run(PowerMockRule.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	... 29 more

Activity code:
@BindView(R.id.titleBar)
    ColorTitleBar titleBar;
    @BindView(R.id.tvTip)
    TextView tvTip;

    @Override
    protected int onLayoutInflater() {
        return R.layout.activity_junit_test;
    }

Layout:
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:orientation="vertical">

    <com.baby.phone.widget.ColorTitleBar
        android:id="@+id/titleBar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@color/white"
        app:showDivider="true"
        app:titleText="@string/title_register"/>

    <TextView
        android:id="@+id/tvTip"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>
</LinearLayout>

unit test code:
    @Test
    public void onLayoutInflater() {
        Activity activity = Robolectric.setupActivity(JunitActivity.class);

//        TextView viewById = activity.findViewById(R.id.tvTip);

        assertNotNull(activity);
    }

**Comment by JakeWharton** [comment]
This is not a problem with Butter Knife. Looks like you have some kind of classpath issues.
