### ISSUE TITLE
Component development cannot find the R2 file

### ISSUE THREAD

**Issue by HexlDL** [JakeWharton/butterknife#1310]
Hi!

I have a very strange problem. My project can use R2.id. to bind view in integrated mode, but I can't find R2 file when the sub-module is running.
The following is my configuration file

> This is Module config

`if (isModule.toBoolean()) {
    apply plugin: 'com.android.application'
} else {
    apply plugin: 'com.android.library'
}

apply plugin: 'com.jakewharton.butterknife'
dependencies {
    //ButterKnife
    com.jakewharton:butterknife:8.8.1
    annotationProcessor com.jakewharton:butterknife-compiler:8.8.1
}
`

> This is app config
`dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        //ButterKnife
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.4.0'
    }
`
Error log:
`Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'packageForR' for task ':airmine:processDebugResources' of type com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.
	at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:83)
	at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:61)
	at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask_Decorated.getProperty(Unknown Source)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:174)
	at groovy.lang.Closure.getPropertyTryThese(Closure.java:312)
	at groovy.lang.Closure.getPropertyDelegateFirst(Closure.java:302)
	at groovy.lang.Closure.getProperty(Closure.java:287)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:50)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
	at **butterknife.plugin.ButterKnifePlugin$_apply_closure1$_closure2$_closure3$_closure4.doCall(ButterKnifePlugin.groovy:31)**
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:718)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:691)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 107 more

`

**Comment by jokermonn** [comment]
may u could try this plugin: [jokermonn/butterknife-gradle-plugin](https://github.com/jokermonn/butterknife-gradle-plugin), but I'm not try to upload this plugin to maven, because butterknife 9.0.0-SNAPSHOT fix this bug, the reason is 8.4.0~8.8.1's plugin just support gradle plugin 2.0+. but [jokermonn/butterknife-gradle-plugin](https://github.com/jokermonn/butterknife-gradle-plugin) supports 3.0+, Or u can use butterknife in 9.0.0-SNAPSHOT(it supports 3.0+)
