### ISSUE TITLE
How to depend on local jar packages(butterknife-compiler) instead of depend on the remote?

### ISSUE THREAD

**Issue by xiaoguidan** [JakeWharton/butterknife#1316]
i want to depend on local jar packages,but it not work。

## Configuration
![snipaste_2018-08-16_16-05-16](https://user-images.githubusercontent.com/8219834/44196510-b9c57480-a16e-11e8-9647-0d8ab362886e.png)
![snipaste_2018-08-16_16-05-45](https://user-images.githubusercontent.com/8219834/44196513-baf6a180-a16e-11e8-86ce-ee81ddb93c2c.png)
![snipaste_2018-08-16_16-06-04](https://user-images.githubusercontent.com/8219834/44196515-bc27ce80-a16e-11e8-921a-2b070d0284c2.png)

## Log

```
16:11:20.704 [DEBUG] [org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler] Compiler arguments: -source 1.7 -target 1.7 -d E:\android\workspace_git\MyApplication\app\build\intermediates\classes\debug -encoding UTF-8 -bootclasspath E:\android\androidSdk\platforms\android-28\android.jar;E:\android\androidSdk\build-tools\27.0.3\core-lambda-stubs.jar -s E:\android\workspace_git\MyApplication\app\build\generated\source\apt\debug -g -sourcepath  -processorpath E:\android\workspace_git\MyApplication\app\libs\butterknife-compiler-8.5.1.jar -XDuseUnsharedTable=true -classpath C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\appcompat-v7-28.0.0-rc01.aar\c433533d04f889c2877813367ef2ef01\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\constraint-layout-1.1.2.aar\372749eeb30ef402a3adcabaa2c9b11f\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\support-fragment-28.0.0-rc01.aar\ada19d11674543993878d649b46932d7\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\animated-vector-drawable-28.0.0-rc01.aar\36e3631b564b36a63a32304b28fafabb\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\support-core-ui-28.0.0-rc01.aar\879be27f97c0c5283f007f09ec1571e0\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\support-core-utils-28.0.0-rc01.aar\2047ba69296d1581e5363363ce57ac02\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\support-vector-drawable-28.0.0-rc01.aar\c6ff8ea0643cc18d4cf00c245a286ea8\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\loader-28.0.0-rc01.aar\483c802a416b8e27f347e0d46af3b5b2\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\viewpager-28.0.0-rc01.aar\c9d51aa5ad1245dccb2ac711f7718615\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\coordinatorlayout-28.0.0-rc01.aar\0811b94dc681c9e8a26a595d59071f81\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\drawerlayout-28.0.0-rc01.aar\9516a32cdbec81d274c4441cc64817b2\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\slidingpanelayout-28.0.0-rc01.aar\03db2da3d0d1afed98f4a80610753a7a\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\customview-28.0.0-rc01.aar\280f786458165740a3fe9de96d340a05\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\swiperefreshlayout-28.0.0-rc01.aar\cad097ce321d0769b8f0e7a570474d2e\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\asynclayoutinflater-28.0.0-rc01.aar\7d2570b5e6e0a2c4aae5325d883b4aa9\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\support-compat-28.0.0-rc01.aar\db717a066a0fc9c64a8d74fb0c62b0b0\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\versionedparcelable-28.0.0-rc01.aar\a2fd069d9cb3a7e58d69b12b155bb2ad\jars\classes.jar;C:\Users\Leo\.gradle\caches\modules-2\files-2.1\com.android.support\collections\28.0.0-rc01\936bb431338ec51ccd899b3bf100b3961af3c25d\collections-28.0.0-rc01.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\cursoradapter-28.0.0-rc01.aar\77426351ed78e297b56cbc479ec3aa09\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\runtime-1.1.1.aar\aa08e9606c36adb8b2feab97a8ece16d\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\documentfile-28.0.0-rc01.aar\06f2eaaa290046ecdb41715714414e93\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\localbroadcastmanager-28.0.0-rc01.aar\f8ca151973dec85b67df553eff78e87e\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\print-28.0.0-rc01.aar\e9be3d5dc7779c7d313000f1e91a72f4\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\viewmodel-1.1.1.aar\6351c25bcf7005d38071d25dfb7deb29\jars\classes.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\livedata-core-1.1.1.aar\f691a30804d20b3bdafa9bd17c0b2d9b\jars\classes.jar;C:\Users\Leo\.gradle\caches\modules-2\files-2.1\android.arch.lifecycle\common\1.1.1\207a6efae6a3555e326de41f76bdadd9a239cbce\common-1.1.1.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\runtime-1.1.1.aar\c33ff0a1a442545fd4d045af3916eade\jars\classes.jar;C:\Users\Leo\.gradle\caches\modules-2\files-2.1\android.arch.core\common\1.1.1\e55b70d1f5620db124b3e85a7f4bdc7bd48d9f95\common-1.1.1.jar;C:\Users\Leo\.gradle\caches\transforms-1\files-1.1\interpolator-28.0.0-rc01.aar\4199fdcda0e974c5b2c872449aa87d50\jars\classes.jar;C:\Users\Leo\.gradle\caches\modules-2\files-2.1\com.android.support\support-annotations\28.0.0-rc01\4fec72569449246ee917f3249147f8e47910b119\support-annotations-28.0.0-rc01.jar;C:\Users\Leo\.gradle\caches\modules-2\files-2.1\com.android.support.constraint\constraint-layout-solver\1.1.2\bfc967828daffc35ba01c9ee204d98b664930a0f\constraint-layout-solver-1.1.2.jar E:\android\workspace_git\MyApplication\app\src\main\java\leo\com\myapplication\MainActivity.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\arch\core\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\arch\lifecycle\livedata\core\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\arch\lifecycle\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\arch\lifecycle\viewmodel\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\support\asynclayoutinflater\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\support\compat\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\support\constraint\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\support\coordinatorlayout\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\support\coreui\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\support\coreutils\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\support\cursoradapter\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\support\customview\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\support\documentfile\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\support\drawerlayout\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\support\fragment\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\support\graphics\drawable\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\support\interpolator\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\support\loader\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\support\localbroadcastmanager\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\support\print\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\support\slidingpanelayout\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\support\swiperefreshlayout\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\support\v7\appcompat\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\android\support\v7\viewpager\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\androidx\versionedparcelable\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\r\debug\leo\com\myapplication\R.java E:\android\workspace_git\MyApplication\app\build\generated\source\buildConfig\debug\leo\com\myapplication\BuildConfig.java
16:11:20.704 [INFO] [org.gradle.api.internal.tasks.compile.JdkJavaCompiler] Compiling with JDK Java compiler API.
16:11:20.891 [ERROR] [system.err] 错误: 服务配置文件不正确, 或构造处理程序对象javax.annotation.processing.Processor: Provider butterknife.compiler.ButterKnifeProcessor could not be instantiated: java.lang.NoClassDefFoundError: com/squareup/javapoet/ClassName时抛出异常错误
16:11:20.891 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Execute compile for :app:compileDebugJavaWithJavac'
16:11:20.891 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 235: dispatching class org.gradle.launcher.daemon.protocol.BuildEvent
16:11:20.891 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Snapshotting property annotationProcessorOutputFolder (OUTPUT) for task ':app:compileDebugJavaWithJavac'
16:11:20.892 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Snapshotting property destinationDir (OUTPUT) for task ':app:compileDebugJavaWithJavac'
16:11:20.892 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Snapshotting property options.annotationProcessorGeneratedSourcesDirectory (OUTPUT) for task ':app:compileDebugJavaWithJavac'
16:11:20.892 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] No discovered inputs for task ':app:compileDebugJavaWithJavac'
16:11:20.892 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Removed task artifact state for {} from context.
16:11:20.892 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':app:compileDebugJavaWithJavac'
16:11:20.892 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] :app:compileDebugJavaWithJavac FAILED
16:11:20.893 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Task :app:compileDebugJavaWithJavac'
16:11:20.893 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 235: dispatching class org.gradle.launcher.daemon.protocol.BuildEvent
16:11:20.893 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Task :app:compileDebugJavaWithJavac' completed
16:11:20.893 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :app:compileDebugJavaWithJavac (Thread[Task worker for ':',5,main]) completed. Took 0.35 secs.
16:11:20.893 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1.7 completed (1 worker(s) in use)
16:11:20.893 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Task worker for ':': released lock on root.1.7
16:11:20.893 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Task worker for ':': released lock on :
16:11:20.893 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Daemon worker Thread 4,5,main]] finished, busy: 1.676 secs, idle: 0.707 secs
16:11:20.893 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':',5,main]] finished, busy: 0.671 secs, idle: 1.708 secs
16:11:20.894 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Run tasks'
16:11:20.894 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 225: dispatching class org.gradle.launcher.daemon.protocol.BuildEvent
16:11:20.895 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
16:11:20.895 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
16:11:20.895 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
16:11:20.895 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
16:11:20.895 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':app:compileDebugJavaWithJavac'.
16:11:20.895 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Compilation failed; see the compiler error output for details.
16:11:20.895 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
16:11:20.895 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
16:11:20.895 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]  Run with --scan to get full insights.
16:11:20.895 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
16:11:20.895 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
16:11:20.895 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJavaWithJavac'.
16:11:20.895 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
16:11:20.895 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
16:11:20.895 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
16:11:20.895 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
16:11:20.895 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
16:11:20.895 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
16:11:20.895 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:50)
16:11:20.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:35)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:98)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:51)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:37)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:39)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:24)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:207)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:133)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:125)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
16:11:20.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 29 more
16:11:20.898 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
16:11:20.898 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
16:11:20.898 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
16:11:20.898 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
16:11:20.898 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 3s
```

**Comment by brudaswen** [comment]
If you are referencing your local jar, all the transitive dependencies are missing.

Add the following dependency could help (untested):
```annotationProcessor 'com.squareup:javapoet:1.10.0'```

**Comment by xiaoguidan** [comment]
@brudaswen i'm try。but it does not work well

**Comment by JakeWharton** [comment]
This is a Gradle question and not a Butter Knife question. You just happen to be using Butter Knife in this instance. Regardless, I don't know the answer. You'd be better off on StackOverflow or the Gradle forums.

**Comment by Wesley-D-Wills** [comment]
when you depend on local jar packages, have a try belows。 Hope it helps you。
   
 implementation files('libs/auto-value-annotations-1.6.2.jar')
    implementation files('libs/auto-common-0.10.jar')
//    implementation files('libs/jsr305-1.3.9.jar')
    implementation files('libs/jsr305-3.0.2.jar')
//    implementation files('libs/error_prone_annotations-2.1.3.jar')
    implementation files('libs/error_prone_annotations-2.3.1.jar')
//    implementation files('libs/guava-24.0-jre.jar')
    implementation files('libs/guava-25.1-android.jar')
    implementation files('libs/j2objc-annotations-1.1.jar')
    implementation files('libs/truth-0.42.jar')
    implementation files('libs/diffutils-1.3.0.jar')
    implementation files('libs/javapoet-1.10.0.jar')
    implementation files('libs/junit-4.12.jar')
    implementation files('libs/incap-0.2.jar')
//    implementation files('libs/checker-compat-qual-2.0.0.jar')
    implementation files('libs/checker-compat-qual-2.5.3.jar')
    implementation files('libs/checker-qual-2.5.3.jar')
    implementation files('libs/animal-sniffer-annotations-1.14.jar')
    implementation files('libs/hamcrest-core-1.3.jar')

    annotationProcessor files('libs/butterknife-compiler-10.2.3.jar')
