### ISSUE TITLE
Butterknife can't bind where findViewById works

### ISSUE THREAD

**Issue by MohMah** [JakeWharton/butterknife#1323]
I have this layout that includes another layout, something like this:
```
<android.support.constraint.ConstraintLayout>

    <include layout="@layout/header_layout" />

</android.support.constraint.ConstraintLayout>
````

I've defined a utility class for the included layout, something like this:
```
public class HeaderComponent {
    @BindView(R.id.headerText)
    TextView headerText;
    @BindView(R.id.backButton)
    ImageButton backButton;

    HeaderComponent(Activity activity) {
        ButterKnife.setDebug(true);
        ButterKnife.bind(activity);
    }
}
```
and in the activity's onCreate we have something like this:
```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_profile);
        header = new HeaderComponent(this);
    }
```
so basically after the constructor call for `HeaderComponent`, `headerText` and `backButton` are `null`. However when I change the constructor to this:
```
    HeaderComponent(Activity activity) {
        headerText = (TextView) activity.findViewById(R.id.headerText);
        backButton = (ImageButton) activity.findViewById(R.id.backButton);
    }
```
they aren't `null` anymore.

**Comment by JakeWharton** [comment]
What does the generated code of `ViewBinding_HeaderComponent` look like? Because it should look exactly like those two lines.

**Comment by MohMah** [comment]
Stacktrace:
```
    java.lang.RuntimeException: Unable to start activity ComponentInfo{.../....ProfileActivity}: java.lang.IllegalArgumentException: Main layout does not include header_layout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2911)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalArgumentException: Main layout does not include header_layout
        at ....HeaderComponent.<init>(HeaderComponent.java:25)
        at ....ProfileActivity.onCreate(ProfileActivity.java:15)
        at android.app.Activity.performCreate(Activity.java:7041)
        at android.app.Activity.performCreate(Activity.java:7032)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1231)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6753) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

**Comment by JakeWharton** [comment]
That exception message isn't coming from Butter Knife. Since codegen is clearly working my best guess would be ProGuard isn't configured properly. Without more information it's impossible to know. From everything you've shown Butter Knife seems to be working correctly.
