### ISSUE TITLE
App crashes after code changes until rebuild is performed

### ISSUE THREAD

**Issue by ernestp** [JakeWharton/butterknife#1365]
Issue similar to https://github.com/JakeWharton/butterknife/issues/957 and https://github.com/JakeWharton/butterknife/issues/864

I'm not using Jack

My gradle rules - https://pastebin.com/RDjfzuDb

**Comment by ernestp** [comment]
Exception:

     Caused by: java.lang.IllegalStateException: Required view 'expanded_menu' with ID 2131296379 for method 'extraTime' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.
        at butterknife.internal.Utils.findRequiredView(Utils.java:92)
        at preved.medved.main.RouteBuilderFragment_ViewBinding.<init>(RouteBuilderFragment_ViewBinding.java:44)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at butterknife.ButterKnife.createBinding(ButterKnife.java:199)
        at butterknife.ButterKnife.bind(ButterKnife.java:172)

**Comment by winterDroid** [comment]
Yeah we have similar issues

**Comment by ChrisTitos** [comment]
Seems to be the same issue as  #897
