### ISSUE TITLE
Cannot create a custom view binding (Butterknife-9.0.0-rc2) and AndroidX

### ISSUE THREAD

**Issue by rahul-narkhede** [JakeWharton/butterknife#1411]
I am creating a custom view class

```
public class ContentRater extends LinearLayout {

    @BindView(R.id.text_was_this_helpful)
    StandardTextView wasThisHelpfulTextView;

	public ContentRater(final Context context) {
        super(context);
        LayoutInflater.from(context).inflate(R.layout.content_rater, this, true);
        ButterKnife.bind(this);
    }

    public ContentRater(final Context context, final AttributeSet attrs, final int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }

    public ContentRater(final Context context, final AttributeSet attrs, final int defStyleAttr, final int defStyleRes) {
        super(context, attrs, defStyleAttr, defStyleRes);
    }

    public ContentRater(final Context context, final AttributeSet attributeSet) {
        super(context, attributeSet);
    }

    @Override
    protected void onFinishInflate() {
        super.onFinishInflate();
        ButterKnife.bind(this);
    }

   @OnClick(R.id.text_was_this_helpful)
    void onClickWhyNotHelpful() {
    }

}
````
The associated xml file is:

````
<?xml version="1.0" encoding="utf-8"?>
<com.content.explorer.view.ContentRater
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <include
        layout="@layout/horizontal_content_divider"/>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="@dimen/header_divider_margin"
        android:orientation="horizontal">

        <com.content.explorer.view.StandardTextView
            android:id="@+id/text_was_this_helpful"
            android:layout_width="0dp"
            android:layout_weight="10"
            android:enabled="false"
            android:gravity="center_vertical"
            android:paddingLeft="0dp"
            android:paddingRight="@dimen/list_view_padding_bottom"
            android:text="@string/was_this_helpful"
            android:textColor="@color/text_0"/>
    </LinearLayout>

</com.content.explorer.view.ContentRater>
````

That class in inflated via XMl from an activity.  The log statements received are: 

````
 D ButterKnife: Looking up binding for com.content.explorer.view.alerts.AlertDetailsHeaderView
 D ButterKnife: HIT: Loaded binding class and constructor.
 D ButterKnife: Looking up binding for com.content.explorer.view.alerts.AlertDetailsListView
 D ButterKnife: Not found. Trying superclass android.widget.LinearLayout
 D ButterKnife: MISS: Reached framework class. Abandoning search.
 D ButterKnife: Looking up binding for com.content.explorer.view.ContentRater
 D ButterKnife: HIT: Loaded binding class and constructor.
````

which notes that class is properly getting generated.  But binding is still null

````
 E AlertActivity: RuntimeException while executing runnable com.google.common.util.concurrent.Futures$4@2a51d2d with executor MoreExecutors.directExecutor()
 E AlertActivity: android.view.InflateException: Binary XML file line #75: Required view 'text_was_this_helpful' with ID 2131297329 for field 'wasThisHelpfulTextView' and method 'onClickWhyNotHelpful' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.
 E AlertActivity: Caused by: java.lang.IllegalStateException: Required view 'text_was_this_helpful' with ID 2131297329 for field 'wasThisHelpfulTextView' and method 'onClickWhyNotHelpful' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.
 E AlertActivity: 	at butterknife.internal.Utils.findRequiredView(Utils.java:88)
 E AlertActivity: 	at com.content.explorer.view.ContentRater_ViewBinding.<init>(ContentRater_ViewBinding.java:34)
 E AlertActivity: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
 E AlertActivity: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
 E AlertActivity: 	at butterknife.ButterKnife.bind(ButterKnife.java:171)
 E AlertActivity: 	at butterknife.ButterKnife.bind(ButterKnife.java:111)
 E AlertActivity: 	at com.content.explorer.view.ContentRater.onFinishInflate(ContentRater.java:108)
 E AlertActivity: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:876)
 E AlertActivity: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
 E AlertActivity: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
 E AlertActivity: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
 E AlertActivity: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
 E AlertActivity: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
 E AlertActivity: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
 E AlertActivity: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
 E AlertActivity: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
 E AlertActivity: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
 E AlertActivity: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
 E AlertActivity: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
 E AlertActivity: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
 E AlertActivity: 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
 E AlertActivity: 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
````

**Comment by mohammedhemaid** [comment]
@rahul-narkhede  how did you bind this view?
