### ISSUE TITLE
butterknife-reflect with multi project setup and R2

### ISSUE THREAD

**Issue by TWiStErRob** [JakeWharton/butterknife#1449]
I was happily adding reflect to a very simple, but multi-module project and bang: it simply crashed with resource not found. Quick stack trace check reveals that reflect is using the value from the annotation as opposed to the name of the R2 constant similar to apt:
```java
public class MainActivity extends AppCompatActivity {
	@Override public void onCreate(@Nullable Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.main_activity);
		ButterKnife.bind(this);
	}
	@OnClick(R2.id.about_button)
	void onAboutClick() { }
```
```
     Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0c0001
        at android.content.res.ResourcesImpl.getResourceEntryName(ResourcesImpl.java:279)
        at android.content.res.Resources.getResourceEntryName(Resources.java:2002)
        at butterknife.internal.Utils.getResourceEntryName(Utils.java:140)
        at butterknife.internal.Utils.findRequiredView(Utils.java:87)
        at butterknife.internal.Utils.findRequiredViewAsType(Utils.java:100)
        at butterknife.ButterKnife.findViews(ButterKnife.java:768)
        at butterknife.ButterKnife.parseOnClick(ButterKnife.java:604)
        at butterknife.ButterKnife.bind(ButterKnife.java:197)
        at butterknife.ButterKnife.bind(ButterKnife.java:68)
        at net.twisterrob.real.main.MainActivity.onCreate(MainActivity.java:24)
```

**Are there any plans for module support, or it's a wet dream?**
A quick thought experiment of what's needed to achieve this feat reveals that from a random class + a number we would need to find the associated `R2` + app's final `R` file to mimic the Butterknife APT:

1. Find `R`/`R2` from `source`/`target` class that was used in annotation: impossible?
1. Find resource name from `R2` class + resource ID: easy
1. Find `R` from `source`/`target`'s Context: easy
1. Find final `R` value from resource name: easy

If not possible, I think we should add a "Compatibility" section into the readme to point this limitation out.

**Comment by JakeWharton** [comment]
As far as I can tell this is impossible without dramatically altering how R2 works.
