### ISSUE TITLE
R2 Resources$NotFoundException

### ISSUE THREAD

**Issue by mnayef95** [JakeWharton/butterknife#1493]
I have an issue with R2, I have project with multiple modules structure
1- core module
2- login module

In login module i'm using android-saripaar which add validation to the EditTexts, in core module i have validation activity which contains boilerplate code, and in  onValidationFailed method i have code like this

``` kotlin
 override fun onValidationFailed(errors: MutableList<ValidationError>?) {
        beginDelayedTransition()
        errors?.forEach { error ->
            if (error.view.parent.parent is TextInputLayout) {
                val paren = (error.view.parent.parent as TextInputLayout)
                paren.isErrorEnabled = true
                paren.error = error.getCollatedErrorMessage(this)
            } else if (error.view is EditText) {
                (error.view as EditText).error = error.getCollatedErrorMessage(this)
            }
        }
    }
```

Now in login module i have login activity which contains code like this

``` kotlin
    @Email(messageResId = R2.string.error_activity_login_email)
    private lateinit var editTextEmail: EditText

    @Password(messageResId = R2.string.error_activity_login_password, min = 8, scheme = Password.Scheme.ALPHA_NUMERIC)
    private lateinit var editTextPassword: EditText
```

now when i call validator.validate in core module i got this exception

```
android.content.res.Resources$NotFoundException: String resource ID #0x7f140047
        at android.content.res.Resources.getText(Resources.java:353)
        at android.content.res.Resources.getString(Resources.java:447)
        at android.content.Context.getString(Context.java:556)
        at com.mobsandgeeks.saripaar.AnnotationRule.getMessage(AnnotationRule.java:64)
        at com.mobsandgeeks.saripaar.ValidationError.getCollatedErrorMessage(ValidationError.java:74)
        at com.example.android.core.activities.BaseValidationActivity.onValidationFailed(BaseValidationActivity.kt:72)
        at com.mobsandgeeks.saripaar.Validator.triggerValidationListenerCallback(Validator.java:721)
        at com.mobsandgeeks.saripaar.Validator.access$100(Validator.java:129)
        at com.mobsandgeeks.saripaar.Validator$AsyncValidationTask.onPostExecute(Validator.java:957)
        at com.mobsandgeeks.saripaar.Validator$AsyncValidationTask.onPostExecute(Validator.java:938)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

I have tried to add these strings to core module but same exception happens
```xml
    <string name="error_activity_login_email" />
    <string name="error_activity_login_password" />
```

I know that the R2 plugin for Butterknife but its good to support multiple cases

**Comment by JakeWharton** [comment]
R2 is only for Butter Knife and requires special handling by an annotation processor. It is not a general purpose utility and its values may change meaning at any time.
