### ISSUE TITLE
Bootstrap Method Error

### ISSUE THREAD

**Issue by cnwobi** [JakeWharton/butterknife#1499]
App crashes with the log 
 Process: au.com.firebasechat, PID: 11834
    java.lang.BootstrapMethodError: Exception from call site #1 bootstrap method
        at butterknife.internal.DebouncingOnClickListener.<clinit>(DebouncingOnClickListener.java:12)
        at au.com.firebasechat.login.ui.LoginActivity_ViewBinding.<init>(LoginActivity_ViewBinding.java:37)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)

Project is set to use Java 8

**Comment by JakeWharton** [comment]
With what version of AGP? Please provide a reproducing sample.

**Comment by cnwobi** [comment]
Hi I updated the AGP and it works now.
Thanks
________________________________
