### ISSUE TITLE
ButterKnife R2 generated file not seen in my project

### ISSUE THREAD

**Issue by amiraelsayed** [JakeWharton/butterknife#1505]
I have a library that use ButterKnife for binding, and as I understand that the resources will be in R2 generated file

the app compile and run but when I try to use a view from my library I got an exception

here is the exception

`android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class im.vector.view.HomeSectionView
    Caused by: android.view.InflateException: Binary XML file line #15: Error inflating class im.vector.view.HomeSectionView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:652)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:95)
        at com.sbs16.ensofia.base.BaseFragment.onCreateView(BaseFragment.kt:28)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f0e00b0
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:202)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2968)
        at android.content.res.Resources.getLayout(Resources.java:1984)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
        at android.view.View.inflate(View.java:22188)
        at im.vector.view.HomeSectionView.setup(HomeSectionView.java:109)
        at im.vector.view.HomeSectionView.<init>(HomeSectionView.java:79)`

and here is my code

`
<im.vector.view.HomeSectionView
                    android:id="@+id/invitations_section"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"/>`

HomeSectionView is found in the library and use resources from R2 file

does anyone face the same problem before ?

**Comment by FreedomMercenary** [comment]
I ran into this same issue when upgrading from 9.x to 10.x.  In the documentation there is now a reference to ButterKnife requiring Java 1.8 and needing a directive added to the app's top level build.gradle under the root android section:

```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

I did a few other things like File->Invalidate Caches/Restart and updating Android Studio but in the end this was the solution for me.

**Comment by Jafar396** [comment]
@amiraelsayed @FreedomMercenary 
I try to merge two project and when I convert the second project to library module the @BindView(R.id.xxx) in library is tell me (attribute value must be a constant) and when I research I add in my library module:
apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife'
and:
compileOptions {
sourceCompatibility JavaVersion.VERSION_1_8
targetCompatibility JavaVersion.VERSION_1_8
}
and:
implementation 'com.jakewharton:butterknife:10.2.1'
annotationProcessor 'com.jakewharton:butterknife-compiler:10.2.1'
and I add in my project:
dependencies {
classpath 'com.android.tools.build:gradle:3.6.1'
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
classpath 'com.jakewharton:butterknife-gradle-plugin:10.2.1'

    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
}
my gradle is 5.6.4
but when I replace R to R2 , The R2 is not found
please help me

**Comment by ridcully99** [comment]
@Jafar396 Make sure that in the 'Build Variants' tab, you have selected the same variant for both modules. By default, for new modules the 'debug' variant is selected there, but if you have a different variant selected for your main module, R2 is not found.
