### ISSUE TITLE
is it bug 

### ISSUE THREAD

**Issue by lianchengtong** [JakeWharton/butterknife#1518]
@OnTextChanged(value = R.id.edit, callback = OnTextChanged.Callback.AFTER_TEXT_CHANGED)
when I upgrade the latest of version to 10.1.0, and it working in 8.6， but now there are no response now when i input word, what is the trouble ?

**Comment by lianchengtong** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.butterknife/com.example.butterknife.library.SimpleActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2841)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2919)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
        at com.example.butterknife.library.SimpleActivity.onCreate(SimpleActivity.java:68)
        at android.app.Activity.performCreate(Activity.java:7074)
        at android.app.Activity.performCreate(Activity.java:7065)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2794)
there have bug in the demo.
can the author run on the demo?

**Comment by JakeWharton** [comment]
Best guess: You forgot a call to ButterKnife.bind or you didn't add the annotation processor. Without more info it's impossible to know. Can you provide a sample which reproduces the behavior?
