### ISSUE TITLE
java.lang.BootstrapMethodError: Exception from call site #0 bootstrap method

### ISSUE THREAD

**Issue by itzhaokun** [JakeWharton/butterknife#1630]
java.lang.BootstrapMethodError: Exception from call site #0 bootstrap method
        at butterknife.Unbinder.<clinit>(Unbinder.java:9)
        at butterknife.ButterKnife.bind(ButterKnife.java:165)
        at butterknife.ButterKnife.bind(ButterKnife.java:99)
        at com.aixuetang.teacher.activities.BaseActivity.onCreate(BaseActivity.java:68)
        at android.app.Activity.performCreate(Activity.java:7248)
        at android.app.Activity.performCreate(Activity.java:7239)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3111)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3266)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7042)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:868)

**Comment by JakeWharton** [comment]
Butter Knife requires Java 8 since version 9.0. You can read about enabling it here: https://developer.android.com/studio/write/java8-support#supported_features
