### ISSUE TITLE
Static member 'null.R2.id' accessed via instance reference

### ISSUE THREAD

**Issue by MBalazs1234** [JakeWharton/butterknife#1703]
I changed from R to R2 but the ID underlines it with the following text:
`Static member 'null.R2.id' accessed via instance reference`

and when I try running the code it throws this error:

```
java.lang.annotation.AnnotationTypeMismatchException: Incorrectly typed data found for annotation element public abstract int butterknife.BindView.value() (Found data of type R2.id)
  	at jdk.compiler/com.sun.tools.javac.model.AnnotationProxyMaker$ValueVisitor$1AnnotationTypeMismatchExceptionProxy.generateException(AnnotationProxyMaker.java:271)
  	at java.base/sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:89)
  	
```

![Screenshot 2024-07-24 at 19 21 54](https://github.com/user-attachments/assets/5116928f-db94-4d8d-be2e-32aa86bf559d)

**Comment by cwiapst** [comment]
I had the same problem

**Comment by diederikMrAwesome** [comment]
The Android Gradle plugin upgraded with the following settings on in the gradle.properties file.

```
android.nonFinalResIds=false
android.nonTransitiveRClass=false
```

This seems to have worked for us.  The longer term solution is still to move to [ViewBinding](https://developer.android.com/topic/libraries/view-binding) however.

**Comment by aiquantong** [comment]
I met the same issue,
