### ISSUE TITLE
Remove listeners in reset

### ISSUE THREAD

**Issue by scompt** [JakeWharton/butterknife#211]
Is there any reason to not remove the listeners as well in the generated `reset()` method? Something like the following:

````
public class ExampleFragment$$ViewInjector {
  public static void inject(Finder finder, final ExampleFragment target, Object source) {
    View view;
    view = finder.findRequiredView(source, 2131493193, "field 'uiList' and method 'onItemClick'");
    target.uiList = (android.widget.ListView) view;
    ((android.widget.AdapterView<?>) view).setOnItemClickListener(
      new android.widget.AdapterView.OnItemClickListener() {
        @Override public void onItemClick(
          android.widget.AdapterView<?> p0,
          android.view.View p1,
          int p2,
          long p3
        ) {
          target.onItemClick(p2);
        }
      });
  }

  public static void reset(ExampleFragment target) {
    // The next line is new!
    target.uiList.setOnItemClickListener(null);
    target.uiList = null;
  }
}
````

**Comment by SimonVT** [comment]
Is there any reason to remove them?

**Comment by JakeWharton** [comment]
Leaks a reference otherwise. Isn't that why you `null` the views in the first place? I've never actually used `reset()`.

**Comment by scompt** [comment]
We're experiencing a `NullPointerException` because the `OnItemClickedListener` is being called after the fragment has been detached. Because we're resetting the fragment in `onDestroyView()`, the views are null leading to the NPE.

Why exactly the listener is being called after the fragment is detached, I haven't figured out. Here's what the stack trace looks like:

````
java.lang.NullPointerException
       at ExampleFragment.onItemClick(ExampleFragment.java:91)
       at ExampleFragment$$ViewInjector$1.onItemClick(ExampleFragment$$ViewInjector.java:20)
       at android.widget.AdapterView.performItemClick(AdapterView.java:308)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1510)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3472)
       at android.widget.AbsListView$3.run(AbsListView.java:4835)
       at android.widget.AbsListView.onDetachedFromWindow(AbsListView.java:3302)
       at android.view.View.dispatchDetachedFromWindow(View.java:13547)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2802)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2800)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2800)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4067)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4040)
       at android.view.ViewGroup.removeView(ViewGroup.java:3972)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1045)
       at android.support.v4.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1223)
       at android.support.v4.app.BackStackRecord.popFromBackStack(BackStackRecord.java:908)
       at android.support.v4.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1541)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:502)
       at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:176)
       at android.support.v7.app.ActionBarActivity.onBackPressed(ActionBarActivity.java:298)
       at android.app.Activity.onKeyUp(Activity.java:2295)
       at android.view.KeyEvent.dispatch(KeyEvent.java:3232)
       at android.app.Activity.dispatchKeyEvent(Activity.java:2529)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2181)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4661)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4628)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4193)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4247)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4216)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4327)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4224)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4384)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4193)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4247)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4216)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4224)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4193)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4247)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4216)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4360)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4520)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2217)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1864)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1855)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2194)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:138)
       at android.os.Looper.loop(Looper.java:131)
       at android.app.ActivityThread.main(ActivityThread.java:5593)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
````

**Comment by JakeWharton** [comment]
It happens like this:

 * Frame 1 ends
 * Java code starts running, posts a fragment transaction to remove fragment.
 * User lets go of the screen, enqueues an ACTION_UP touch event.
 * Java code finishes running.
 * Frame 2 happens
 * Fragment manager runs and detaches the fragment calling onDestroyView in the process.
 * Touch event is delivered, interpreted as the end of a click, onClick is fired.
 * On click callback happens, fragment has its views nulled out.

**Comment by scompt** [comment]
Thanks for the explanation!

It sounds like a PR for this would probably be accepted?

**Comment by JakeWharton** [comment]
Yep. I think this makes sense as a change.

**Comment by JakeWharton** [comment]
Going to try to do this today.

**Comment by JakeWharton** [comment]
This is actually somewhat impossible as it stands right now since we usually do not have a reference to the view.

**Comment by scompt** [comment]
Would the right way be to reuse the finders/etc from `inject` to get the view into the generated reset method?

**Comment by JakeWharton** [comment]
No. The view layout might have changed causing different views to be found.

I have a plan for this. Basically, you'll inject a `Resetter` (name not finalized) which will maintain the references and rather than call `ButterKnife.reset(this)` you'll directly call `resetter.reset()`.

**Comment by kelticknight** [comment]
Hey @JakeWharton ,

Have you made any progress on this. I really need this right now. Without this, you get NPEs very easily.

Easy reproduce steps:
1) Attach on focus changed to a edit text in a fragment and try to access any bounded view in the lister
2) Unbind butterknife in the fragment, as we should
3) Set the focus in the bounded edit text
4) Press the back button to navigate from the fragment
5) NPE 

This particular NPE occurs since the onDestroyView is called when the back button is pressed so the fields are nullified and then the focus is removed from the view as it's going through the delete cycle, and hence the listener is called after bounded the fields have been nullified. ipso facto NPE

This is particular problematic since event binders like OnTextChanged are done with the actual pointer to the TextWatch boilerplate code tucked away likely inside the generated code, which prevents us from manually removing it from the watch chain in the onDestroyView, so we'll have to wait for you to add the removal to the library.

 Any updates would be greatly appreciated. BTW, thanks for the great lib ;)

**Comment by JakeWharton** [comment]
No updates. I don't use fragments so the incentive to work on this is low.
I would happily accept a contribution along the lines of what I said above.

**Comment by grub-** [comment]
Same here, not using reset on fragments for now because of this issue.

**Comment by Rbcum** [comment]
probably a handler.post would fix this

**Comment by JakeWharton** [comment]
It wouldn't.

**Comment by scompt** [comment]
@JakeWharton Were you thinking of something like this?

```
public class MyFragment extends Fragment {

  @Bind(R.id.title) TextView title;
  @BindUnbinder Unbinder unbinder;

  @Override
  public void onViewCreated(View view, Bundle savedInstanceState) {
    super.onViewCreated(view, savedInstanceState);
    ButterKnife.bind(this, view);
  }
  
  @Override
  public void onDestroyView() {
    super.onDestroyView();
    unbinder.unbind();
  }
  
  @OnClick(R.id.hello) void sayHello() {
    ...
  }
}

public class MyFragment$$Unbinder<T extends MyFragment> implements Butterknife.Unbinder<T> {

  private WeakReference<View> sayHelloReference;
  
  public void unbind(T target) {
    View sayHello = sayHelloReference.get();
	if (sayHello != null) {
	  sayHello.setOnClickListener(null);
	}
	
	target.title = null;
  }
}
```

**Comment by JakeWharton** [comment]
Yep, something close to that. And without the weak reference :grinning:

**Comment by serj-lotutovici** [comment]
Is somebody working on this issue? If not, I have some time I can dedicate to it...

**Comment by scompt** [comment]
I haven't done anything for this issue, just extrapolated jake's idea into code.

**Comment by serj-lotutovici** [comment]
@scompt I you don't mind, I can try to implement that idea :) I really would like to see this feature in 8.0.0 release.

**Comment by scompt** [comment]
@serj-lotutovici Go for it! I would too, but don't have the time at the moment to implement it.
