### ISSUE TITLE
Looking up an ID name can fail and throw.

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/butterknife#232]
```
java.lang.UnsupportedOperationException
	at android.content.res.BridgeResources.getResourceTypeName(BridgeResources.java:485)
	at android.view.View.toString(View.java:4295)
	at java.lang.String.valueOf(String.java:2826)
	at java.lang.StringBuilder.append(StringBuilder.java:115)
	at butterknife.ButterKnife.inject(ButterKnife.java:282)
	at butterknife.ButterKnife.inject(ButterKnife.java:194)
```

**Comment by JakeWharton** [comment]
Actually this might not be our problem...

**Comment by JakeWharton** [comment]
4daa4e4f6c73f90352fb67201e289d464a828cc8
