### ISSUE TITLE
NoClassDefFoundError: butterknife.internal.ButterKnifeProcessor

### ISSUE THREAD

**Issue by dnish** [JakeWharton/butterknife#236]
Hello everyone,
my app crashes directly at start on Android 5.0.1 smartphones. I've tested it with a HTC M8. On a HTC M7 with Android 5.0.2 and other devices with 4.x everything runs fine.

I'm getting this information from my logs:

java.lang.NoClassDefFoundError: butterknife.internal.ButterKnifeProcessor
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:308)
at com.activeandroid.ReflectionUtils.getModelClasses(ReflectionUtils.java:83)
at com.activeandroid.DatabaseHelper.onCreate(DatabaseHelper.java:46)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
at com.activeandroid.Registry.openDatabase(Registry.java:149)
at com.activeandroid.Registry.initialize(Registry.java:107)
at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:8)
at com.activeandroid.app.Application.onCreate(Application.java:9)
at com.app.fun.myapp3.myapp.onCreate(myapp.java:15)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5009)
at android.app.ActivityThread.access$1600(ActivityThread.java:172)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5834)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)

I'm using the current ButterKnife version (with Eclipse SDK). When I completely remove ButterKnife from my project, everything works fine again.

**Comment by JakeWharton** [comment]
Looks like ActiveAndroid is doing some kind of reflection on classes it shouldn't be. File a bug on that project, there's nothing wrong with ButterKnife here.

**Comment by voronnenok** [comment]
here the solution!
http://stackoverflow.com/questions/23907037/how-to-disable-scanning-for-model-in-activeandroid/
You need to disable scanning for model in activeandroid by defining it in manifest or using Configuration.Builder.  
Heres' link for newest activeandroid jar version. Without that new version crash will be appear again
