### ISSUE TITLE
java.lang.NoClassDefFoundError: android/view/View

### ISSUE THREAD

**Issue by iyy** [JakeWharton/butterknife#329]
Version:7.0.2-SNAPSHOT

when i execute "gradle installD" in android studio ,an error occurs like below:

* What went wrong:
Execution failed for task ':app:compileDebugJava'.
> java.lang.NoClassDefFoundError: android/view/View

**Comment by JakeWharton** [comment]
Paste a full stack trace

**Comment by MichaelEvans** [comment]
@JakeWharton I ran into this last night, I fixed it in #330 whenever it gets merged. I can fix it separately from that PR though

**Comment by iyy** [comment]
a full stack trace:
=============
12:08:44.105 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :butterknifesample:compileDebugJava (Thread[Task worker,5,main]) started.
12:08:44.106 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :butterknifesample:compileDebugJava
12:08:44.106 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':butterknifesample:compileDebugJava'
12:08:44.110 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':butterknifesample:compileDebugJava' is up-to-date
12:08:44.125 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':butterknifesample:compileDebugJava' (up-to-date check took 0.014 secs) due to:
  No history is available.
12:08:44.125 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':butterknifesample:compileDebugJava'.
12:08:44.140 [INFO] [org.gradle.api.internal.changedetection.changes.RebuildIncrementalTaskInputs] All input files are considered out-of-date for incremental task ':butterknifesample:compileDebugJava'.
12:08:44.156 [DEBUG] [org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler] Compiler arguments: -d /home/wangwei/data/opensouce/Fitness2/butterknifesample/build/intermediates/classes/debug -g -encoding UTF-8 -bootclasspath /home/wangwei/Env/bak/adt-bundle-linux-x86_64-20140702/sdk/platforms/android-22/android.jar -sourcepath /home/wangwei/data/opensouce/Fitness2/butterknifesample/build/tmp/compileDebugJava/emptySourcePathRef -s /home/wangwei/data/opensouce/Fitness2/butterknifesample/build/generated/source/apt/debug -processorpath /home/wangwei/.gradle/caches/modules-2/files-2.1/com.jakewharton/butterknife-compiler/7.0.2-SNAPSHOT/eb75643954cc8d28c6e2826d9afcb3d0972ff4c8/butterknife-compiler-7.0.2-SNAPSHOT.jar:/home/wangwei/Env/bak/adt-bundle-linux-x86_64-20140702/sdk/extras/android/m2repository/com/android/support/appcompat-v7/22.2.1/appcompat-v7-22.2.1.aar:/home/wangwei/.gradle/caches/modules-2/files-2.1/com.jakewharton/butterknife/7.0.2-SNAPSHOT/1989eca48d274a80ed0a8e1ac3d9ffe9420635d0/butterknife-7.0.2-SNAPSHOT.jar:/home/wangwei/.gradle/caches/modules-2/files-2.1/com.squareup/javapoet/1.2.0/ad3ba65c1788f4d814a4da056323e2b84412fb3c/javapoet-1.2.0.jar:/home/wangwei/Env/bak/adt-bundle-linux-x86_64-20140702/sdk/extras/android/m2repository/com/android/support/support-v4/22.2.1/support-v4-22.2.1.aar:/home/wangwei/Env/bak/adt-bundle-linux-x86_64-20140702/sdk/extras/android/m2repository/com/android/support/support-annotations/22.2.1/support-annotations-22.2.1.jar:/home/wangwei/data/opensouce/Fitness2/butterknifesample/build/intermediates/exploded-aar/com.android.support/support-v4/22.2.1/jars/classes.jar:/home/wangwei/data/opensouce/Fitness2/butterknifesample/build/intermediates/exploded-aar/com.android.support/support-v4/22.2.1/jars/libs/internal_impl-22.2.1.jar:/home/wangwei/data/opensouce/Fitness2/butterknifesample/build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.2.1/jars/classes.jar -classpath /home/wangwei/Env/bak/adt-bundle-linux-x86_64-20140702/sdk/extras/android/m2repository/com/android/support/support-annotations/22.2.1/support-annotations-22.2.1.jar:/home/wangwei/data/opensouce/Fitness2/butterknifesample/build/intermediates/exploded-aar/com.android.support/support-v4/22.2.1/jars/classes.jar:/home/wangwei/.gradle/caches/modules-2/files-2.1/com.jakewharton/butterknife/7.0.2-SNAPSHOT/1989eca48d274a80ed0a8e1ac3d9ffe9420635d0/butterknife-7.0.2-SNAPSHOT.jar:/home/wangwei/data/opensouce/Fitness2/butterknifesample/build/intermediates/exploded-aar/com.android.support/support-v4/22.2.1/jars/libs/internal_impl-22.2.1.jar:/home/wangwei/data/opensouce/Fitness2/butterknifesample/build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.2.1/jars/classes.jar /home/wangwei/data/opensouce/Fitness2/butterknifesample/src/main/java/raptors/com/butterknifesample/MainActivity.java /home/wangwei/data/opensouce/Fitness2/butterknifesample/build/generated/source/r/debug/android/support/v7/appcompat/R.java /home/wangwei/data/opensouce/Fitness2/butterknifesample/build/generated/source/r/debug/raptors/com/butterknifesample/R.java /home/wangwei/data/opensouce/Fitness2/butterknifesample/build/generated/source/buildConfig/debug/raptors/com/butterknifesample/BuildConfig.java -XDuseUnsharedTable=true
12:08:44.157 [INFO] [org.gradle.api.internal.tasks.compile.JdkJavaCompiler] Compiling with JDK Java compiler API.
12:08:44.643 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':butterknifesample:compileDebugJava'
12:08:44.643 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :butterknifesample:compileDebugJava FAILED
12:08:44.644 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :butterknifesample:compileDebugJava (Thread[Task worker,5,main]) completed. Took 0.538 secs.
12:08:44.644 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Task worker Thread 5,5,main]] finished, busy: 0.167 secs, idle: 0.837 secs
12:08:44.644 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Task worker,5,main]] finished, busy: 0.592 secs, idle: 0.412 secs
12:08:44.644 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Task worker Thread 7,5,main]] finished, busy: 0.028 secs, idle: 0.975 secs
12:08:44.644 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker,5,main]] finished, busy: 0.007 secs, idle: 0.997 secs
12:08:44.644 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Task worker Thread 4,5,main]] finished, busy: 0.035 secs, idle: 0.969 secs
12:08:44.644 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Task worker Thread 3,5,main]] finished, busy: 0.117 secs, idle: 0.887 secs
12:08:44.644 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Task worker Thread 6,5,main]] finished, busy: 0.012 secs, idle: 0.992 secs
12:08:44.644 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Task worker Thread 2,5,main]] finished, busy: 0.038 secs, idle: 0.966 secs
12:08:44.651 [ERROR] [org.gradle.BuildExceptionReporter] 
12:08:44.652 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
12:08:44.653 [ERROR] [org.gradle.BuildExceptionReporter] 
12:08:44.653 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
12:08:44.653 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':butterknifesample:compileDebugJava'.
12:08:44.653 [ERROR] [org.gradle.BuildExceptionReporter] > java.lang.NoClassDefFoundError: android/view/View
12:08:44.653 [ERROR] [org.gradle.BuildExceptionReporter] 
12:08:44.654 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
12:08:44.654 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
12:08:44.655 [LIFECYCLE] [org.gradle.BuildResultLogger] 
12:08:44.655 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
12:08:44.655 [LIFECYCLE] [org.gradle.BuildResultLogger] 
12:08:44.655 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 8.286 secs

**Comment by yrom** [comment]
Ran into the same problem, v7.0.2 SNAPSHOT

````
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJava'.
> java.lang.NoClassDefFoundError: android/view/View
````

stack trace:
````
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJava'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:310)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: android/view/View
	at com.sun.tools.javac.main.Main.compile(Main.java:469)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:132)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:45)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:101)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:157)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:137)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:91)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:243)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:230)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 14 more
Caused by: java.lang.NoClassDefFoundError: android/view/View
	at butterknife.internal.BindingClass.createBindMethod(BindingClass.java:129)
	at butterknife.internal.BindingClass.brewJava(BindingClass.java:106)
	at butterknife.internal.ButterKnifeProcessor.process(ButterKnifeProcessor.java:130)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
	at com.sun.tools.javac.main.Main.compile(Main.java:439)
	... 32 more
Caused by: java.lang.ClassNotFoundException: android.view.View
	... 43 more
````

**Comment by JakeWharton** [comment]
The compiler no longer references Android classes directly. This will be fixed in the next release.
