### ISSUE TITLE
Binder RuntimeException from the binder stub implementation.

### ISSUE THREAD

**Issue by danielgomezrico** [JakeWharton/butterknife#337]
Not sure if this is a butterknife bug but sometimes I get an error

* SDK 23
* Support libs 23.0.0
* Gradle plugin: 1.3.0
* Gradle: 2.6

```
 W/Binder﹕ Caught a RuntimeException from the binder stub implementation.
    java.lang.NullPointerException
            at android.view.WindowManagerGlobal.dumpGfxInfo(WindowManagerGlobal.java:449)
            at android.app.ActivityThread$ApplicationThread.dumpGfxInfo(ActivityThread.java:1116)
            at android.app.ApplicationThreadNative.onTransact(ApplicationThreadNative.java:582)
            at android.os.Binder.execTransact(Binder.java:404)
            at dalvik.system.NativeStart.run(Native Method)
```

**Comment by JakeWharton** [comment]
That stacktrace doesn't include ButterKnife code and that's a binder problem which is something ButterKnife doesn't use. This almost certainly has nothing to do with this library.

**Comment by danielgomezrico** [comment]
:+1: just saw Binder and get confused, sorry.

**Comment by Shanmugapriyan22** [comment]
@caipivara I am also getting the same log. What is the issue ?
