### ISSUE TITLE
Unable to bind views for ViewHolder

### ISSUE THREAD

**Issue by bluejamesbond** [JakeWharton/butterknife#423]
```java
public class CustomViewHolder extends RecyclerView.ViewHolder {
  @Nullable @Bind(R.id.view1) public View mView1;
  @Nullable @Bind(R.id.view2) public View mView2;
   ....
   public CustomViewHolder(View view) {
    super(view);

    assert view != null;

    ButterKnife.bind(this, view); // line 22
  }
}
```

**Not sure why I keep hitting the following error.**
```
java.lang.RuntimeException: Unable to bind views for  ....holders.CustomViewHolder
                   at butterknife.ButterKnife.bind(ButterKnife.java:322)
                   at butterknife.ButterKnife.bind(ButterKnife.java:279)
                   at ...holders.CustomViewHolder.<init>(CustomViewHolder.java:22)
```

**Comment by JakeWharton** [comment]
Paste the full trace

**Comment by bluejamesbond** [comment]
```
12-23 21:57:51.067 21884-21884/com.bemk.pcdealsandroid E/AndroidRuntime: FATAL EXCEPTION: main
          Process: com.bemk.pcdealsandroid, PID: 21884
          java.lang.RuntimeException: Unable to bind views for com.bemk.pcdealsandroid.adapters.holders.PostViewHolder
              at butterknife.ButterKnife.bind(ButterKnife.java:322)
              at butterknife.ButterKnife.bind(ButterKnife.java:279)
              at com.bemk.pcdealsandroid.adapters.holders.PostViewHolder.<init>(PostViewHolder.java:44)
              at com.bemk.pcdealsandroid.adapters.PostAdapter.onCreateListItemViewHolder(PostAdapter.java:71)
              at com.bemk.pcdealsandroid.adapters.BaseAdapter.onCreateViewHolder(BaseAdapter.java:161)
              at com.bemk.pcdealsandroid.adapters.BaseAdapter.onCreateViewHolder(BaseAdapter.java:24)
              at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:4121)
              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3431)
              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3340)
              at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1810)
              at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1306)
              at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1269)
              at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:523)
              at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:1988)
              at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2237)
              at android.view.View.layout(View.java:16630)
              at android.view.ViewGroup.layout(ViewGroup.java:5437)
              at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:584)
              at android.view.View.layout(View.java:16630)
              at android.view.ViewGroup.layout(ViewGroup.java:5437)
              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
              at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
              at android.view.View.layout(View.java:16630)
              at android.view.ViewGroup.layout(ViewGroup.java:5437)
              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
              at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
              at android.view.View.layout(View.java:16630)
              at android.view.ViewGroup.layout(ViewGroup.java:5437)
              at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
              at android.view.View.layout(View.java:16630)
              at android.view.ViewGroup.layout(ViewGroup.java:5437)
              at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
              at android.view.View.layout(View.java:16630)
              at android.view.ViewGroup.layout(ViewGroup.java:5437)
              at com.jeremyfeinstein.slidingmenu.lib.CustomViewAbove.onLayout(CustomViewAbove.java:476)
              at android.view.View.layout(View.java:16630)
              at android.view.ViewGroup.layout(ViewGroup.java:5437)
              at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
              at android.view.View.layout(View.java:16630)
              at android.view.ViewGroup.layout(ViewGroup.java:5437)
              at com.jeremyfeinstein.slidingmenu.lib.CustomViewAbove.onLayout(CustomViewAbove.java:476)
              at android.view.View.layout(View.java:16630)
              at android.view.ViewGroup.layout(ViewGroup.java:5437)
              at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
              at android.view.View.layout(View.java:16630)
              at android.view.ViewGroup.layout(ViewGroup.java:5437)
              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
              at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
              at android.view.View.layout(View.java:16630)
              at android.view.ViewGroup.layout(ViewGroup.java:5437)
              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
              at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
              at android.view.View.layout(View.java:16630)
              at android.view.ViewGroup.layout(ViewGroup.java:5437)
              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
              at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
             at com.android.internal.policy.P
12-23 22:02:51.172 21884-21884/com.bemk.pcdealsandroid I/Process: Sending signal. PID: 21884 SIG: 9
```

**Comment by bluejamesbond** [comment]
Oops! Seems like I goofed up. Anyways, my takeaway. 

Since the original Exception which caused the error is passed into a new RuntimeException ([here](https://github.com/JakeWharton/butterknife/blob/master/butterknife/src/main/java/butterknife/ButterKnife.java#L193)), a better debug output can be seen when you wrap the binding with a try/catch. This will expose the "Caused by" exception (Android Studio 1.5)

```java
try {
    ButterKnife.bind(this, view);
} catch (Exception e) {
    e.printStackTrace();
}
```

**Comment by JakeWharton** [comment]
Yeah this is a problem for long traces inside of Android's code to handle printing these out. Glad you got it resolved, anyway.

**Comment by harry-nguyen-88** [comment]
Hi Jake, I wonder how we can unbind view for recycler's view holder ?  I cannot find any destructor method for view holder so It can lead to memory leak issue in future!

**Comment by timusus** [comment]
@harry-nguyen-88 you can add a `RecyclerListener` to the `RecyclerView`, keep a reference to the binding in the `ViewHolder`, and then call `viewHolder.unbinder.unbind()` in `onViewRecycled`.
