### ISSUE TITLE
ClassCastException for Unbinder of subclass

### ISSUE THREAD

**Issue by gabrielittner** [JakeWharton/butterknife#534]
The problem seems to be that the `ScrollableDialog$$ViewBinder` doesn't override `createUnbinder()`. `ScrollableDialog` is a subclass of `SimpleDialog` which is a `FrameLayout`. I'm using 8.0.1 and binding without inheritance works without any issues. 
The stacktrace:
```
Caused by: java.lang.ClassCastException: com.gabrielittner.timetable.app.view.dialog.SimpleDialog$$ViewBinder$InnerUnbinder cannot be cast to com.gabrielittner.timetable.app.view.dialog.ScrollableDialog$$ViewBinder$InnerUnbinder
                at com.gabrielittner.timetable.app.view.dialog.ScrollableDialog$$ViewBinder.bind(ScrollableDialog$$ViewBinder.java:13)
                at com.gabrielittner.timetable.app.view.dialog.ScrollableDialog$$ViewBinder.bind(ScrollableDialog$$ViewBinder.java:10)
                at butterknife.ButterKnife.bind(ButterKnife.java:187)
                at butterknife.ButterKnife.bind(ButterKnife.java:133) 
                at com.gabrielittner.timetable.app.view.dialog.SimpleDialog.onFinishInflate(SimpleDialog.java:81) 
```

The generated ViewBinders:
```
public final class ScrollableDialog$$ViewBinder<T extends ScrollableDialog> extends SimpleDialog$$ViewBinder<T> {
  @Override
  public Unbinder bind(final Finder finder, final T target, Object source) {
    InnerUnbinder unbinder = (InnerUnbinder) super.bind(finder, target, source);
    View view;
    view = finder.findRequiredView(source, 2131755353, "field 'scrollView'");
    target.scrollView = finder.castView(view, 2131755353, "field 'scrollView'");
    view = finder.findRequiredView(source, 2131755349, "field 'dividerTop'");
    target.dividerTop = view;
    view = finder.findRequiredView(source, 2131755351, "field 'dividerBottom'");
    target.dividerBottom = view;
    return unbinder;
  }

  protected static final class InnerUnbinder<T extends ScrollableDialog> extends SimpleDialog$$ViewBinder.InnerUnbinder<T> {
    protected InnerUnbinder(T target) {
      super(target);
    }
  }
}
```
```
public class SimpleDialog$$ViewBinder<T extends SimpleDialog> implements ViewBinder<T> {
  @Override
  public Unbinder bind(final Finder finder, final T target, Object source) {
    InnerUnbinder unbinder = createUnbinder(target);
    View view;
    view = finder.findRequiredView(source, 2131755347, "field 'container'");
    target.container = finder.castView(view, 2131755347, "field 'container'");
    view = finder.findRequiredView(source, 2131755348, "field 'title'");
    target.title = finder.castView(view, 2131755348, "field 'title'");
    view = finder.findRequiredView(source, 2131755352, "field 'spaceBottom'");
    target.spaceBottom = view;
    view = finder.findRequiredView(source, 16908313, "field 'positiveButton'");
    target.positiveButton = finder.castView(view, 16908313, "field 'positiveButton'");
    view = finder.findRequiredView(source, 16908314, "field 'negativeButton'");
    target.negativeButton = finder.castView(view, 16908314, "field 'negativeButton'");
    view = finder.findRequiredView(source, 16908315, "field 'neutralButton'");
    target.neutralButton = finder.castView(view, 16908315, "field 'neutralButton'");
    return unbinder;
  }

  protected InnerUnbinder<T> createUnbinder(T target) {
    return new InnerUnbinder(target);
  }

  protected static class InnerUnbinder<T extends SimpleDialog> implements Unbinder {
    private T target;

    protected InnerUnbinder(T target) {
      this.target = target;
    }

    @Override
    public final void unbind() {
      if (target == null) throw new IllegalStateException("Bindings already cleared.");
      unbind(target);
      target = null;
    }

    protected void unbind(T target) {
      target.container = null;
      target.title = null;
      target.spaceBottom = null;
      target.positiveButton = null;
      target.negativeButton = null;
      target.neutralButton = null;
    }
  }
}
```

**Comment by gabrielittner** [comment]
Just noticing, shouldn't the `Unbinder` of `ScrollableDialog$$ViewBinder` set the three views bound there to null? If I'm not missing anything I'll open a seperate issue for that.

**Comment by gabrielittner** [comment]
Downgrading to 8.0.0 or removing `final` from `ScrollableDialog` fixes it. Seems to be caused by the changes in #503
