### ISSUE TITLE
Issue With DrawerLayout

### ISSUE THREAD

**Issue by itsbharatbb** [JakeWharton/butterknife#598]
@BindView with android.support.v4.widget.DrawerLayout resulted in Exception

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example/com.example.MainActivity}: java.lang.NullPointerException
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
                                                                             at android.app.ActivityThread.access$600(ActivityThread.java:130)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                             at android.os.Looper.loop(Looper.java:137)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:511)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                             at dalvik.system.NativeStart.main(Native Method)
                                                                          Caused by: java.lang.NullPointerException
                                                                             at com.incmet.examprep.ssc.MainActivity.onCreate(MainActivity.java:36)
                                                                             at android.app.Activity.performCreate(Activity.java:5008)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                                             at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                             at android.os.Looper.loop(Looper.java:137) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                             at dalvik.system.NativeStart.main(Native Method) 

```

**Comment by JakeWharton** [comment]
Looks like you haven't enabled the annotation processor. See the README for instructions.
