### ISSUE TITLE
BindColor cannot get resource 

### ISSUE THREAD

**Issue by eterrao** [JakeWharton/butterknife#600]
**When I set like this:**
   @BindColor(R.color.swipe_refresh_color)
    int refreshRed;

**And use it :**
    mSwipeRefreshLayout.setColorSchemeResources(refreshRed);

I got the bug reporter:
    
    Stack trace:  
    android.content.res.Resources$NotFoundException: Resource ID #0xffff4444
	at android.content.res.Resources.getValue(Resources.java:1369)
	at android.content.res.MiuiResources.getValue(MiuiResources.java:145)
	at android.content.res.Resources.getColor(Resources.java:981)
	at android.content.res.Resources.getColor(Resources.java:954)
	at  android.support.v4.widget.SwipeRefreshLayout.setColorSchemeResources(SwipeRefreshLayout.java:529)
	at com.rayclear.renrenjiang.ui.fragment.GlobalFragmentV2.onCreateView(GlobalFragmentV2.java:123)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
	at android.view.View.measure(View.java:18797)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
	at android.view.View.measure(View.java:18797)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:18797)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
	at android.view.View.measure(View.java:18797)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:18797)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
	at android.view.View.measure(View.java:18797)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2645)
	at android.view.View.measure(View.java:18797)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2136)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1252)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1488)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1143)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6054)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
	at android.view.Choreographer.doCallbacks(Choreographer.java:672)
	at android.view.Choreographer.doFrame(Choreographer.java:608)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5456)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:735)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)

I don't know how to fix this problem

**Comment by JakeWharton** [comment]
BindColor returns a raw color value and you are passing it to a method that
wants a color reference. Either just pass R.color.whatever to that method
or call a different method that accepts a color value.

**Comment by eterrao** [comment]
Thank you so much! 😀 I fixed it, and SwipeRefreshLayout has another method : 
      
    setColorSchemeColors(int... colors) 

So BindColor is working~
