### ISSUE TITLE
java.lang.RuntimeException: Unable to bind views for ViewHolder

### ISSUE THREAD

**Issue by wangxinarhat** [JakeWharton/butterknife#619]
```java
java.lang.RuntimeException: Unable to bind views for cn.wangqiujia.wangqiujia.order.OrderCourseHolder
                                                                      at butterknife.ButterKnife.bind(ButterKnife.java:322)
                                                                      at butterknife.ButterKnife.bind(ButterKnife.java:279)
                                                                      at *my packagename*.order.OrderCourseHolder.<init>(OrderCourseHolder.java:73)
                                                                      at *my packagename*.order.OrderListAdapter.myOnCreateViewHolder(OrderListAdapter.java:64)
                                                                      at *my packagename*.adapter.LoadMoreAdapter.onCreateViewHolder(LoadMoreAdapter.java:38)
                                                                      at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5482)
                                                                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4707)
                                                                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
                                                                      at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
                                                                      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
                                                                      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                                                                      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
                                                                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3028)
                                                                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2906)
                                                                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3283)
                                                                      at android.view.View.layout(View.java:16639)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                      at in.srain.cube.views.ptr.PtrFrameLayout.layoutChildren(PtrFrameLayout.java:264)
                                                                      at in.srain.cube.views.ptr.PtrFrameLayout.onLayout(PtrFrameLayout.java:233)
                                                                      at android.view.View.layout(View.java:16639)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                      at android.view.View.layout(View.java:16639)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                      at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1695)
                                                                      at android.view.View.layout(View.java:16639)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                      at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:122)
                                                                      at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                      at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1192)
                                                                      at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:814)
                                                                      at android.view.View.layout(View.java:16639)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                      at android.view.View.layout(View.java:16639)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
                                                                      at android.view.View.layout(View.java:16639)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                      at android.view.View.layout(View.java:16639)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
                                                                      at android.view.View.layout(View.java:16639)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                      at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2934)
                                                                  	at android.view.View.layout(Vie
                                                                  
                                                                  --------- beginning of crash
```

I just use  like this:

```java
public MyHolder(View itemView) {
	super(itemView);
	ButterKnife.bind(this, itemView);        
}
```

**Comment by JakeWharton** [comment]
Looks like the actual cause is being truncated. Please log the exception cause.

**Comment by wangxinarhat** [comment]
fix it ,like this:
```java
 public OrderVariableHolder(View itemView,  int category) {
        super(itemView);
        try {
            ButterKnife.bind(this, itemView);
        } catch (Exception e) {
            e.printStackTrace();
        }
 }
```
but I stil confuse

**Comment by JakeWharton** [comment]
Try e.getCause().printStackTrace()

**Comment by wangxinarhat** [comment]
I  tried it, but did not print out any exception info ，and then remove the part of the code to catch the exception , not the exception to reappear。so sad...
