### ISSUE TITLE
String resource ID not found in include view

### ISSUE THREAD

**Issue by sannysinghs** [JakeWharton/butterknife#645]
Finding resource id `(R.id.lbl_like_text)` inside `<include>` tag throw null pointer exception. 
**main.xml**

```
..
..
 <TextView
            android:text="@string/dummy_date"
            android:id="@+id/lbl_time"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignStart="@id/lbl_author"
            android:layout_alignLeft="@id/lbl_author"
            android:layout_below="@id/lbl_author"/>

    <include
        android:id="@+id/common_action"
        layout="@layout/common_action"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />


</LinearLayout>
```
**common_action.xml**
```
<LinearLayout android:id="@+id/linNumbers"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:layout_margin="10dp"
        android:orientation="horizontal">

        <TextView
            android:id="@+id/lbl_like_text"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textColor="#888888" />
```

**build.gradle**
```
compile "com.jakewharton:butterknife:$rootProject.ext.butterKnife"
  apt     "com.jakewharton:butterknife-compiler:$rootProject.ext.butterKnife"
```

**viewholder**

```
protected static class ArticleViewHolder extends RecyclerView.ViewHolder {
        @BindView(R.id.lbl_time)
        TextView lblTime;
        @BindView(R.id.lbl_like_text)
        TextView lblLikeText;
        ArticleViewHolder(View view) {
            super(view);
            ButterKnife.bind(this, view);
        }
    }
```

**Error log**
```
06-23 10:21:18.306 12216-12216/com.example.fresco E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.example.fresco, PID: 12216
                                                                      android.content.res.Resources$NotFoundException: String resource ID #0x0
                                                                          at android.content.res.Resources.getText(Resources.java:1419)
                                                                          at android.support.v7.widget.ResourcesWrapper.getText(ResourcesWrapper.java:52)
                                                                          at android.widget.TextView.setText(TextView.java:4947)

```

**Comment by JakeWharton** [comment]
This is not a null pointer exception. You are calling `setText(0)` somewhere which is not a valid string resource.
