### ISSUE TITLE
Upgrade 7.0.1 to 8.1.0 configuration issue

### ISSUE THREAD

**Issue by niqo01** [JakeWharton/butterknife#661]
After upgrading from Butterknife 7.0.1 to 8.1.0, I get the following issue when the app starts:

```
Process: com.couchsurfing.mobile.android, PID: 7976 
java.lang.RuntimeException: Unable to create application com.couchsurfing.mobile.CsApp: java.lang.IllegalStateException: Module adapter for class com.couchsurfing.mobile.c could not be loaded. Please ensure that code generation was run for this module.
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4715)
    at android.app.ActivityThread.-wrap1(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5422)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalStateException: Module adapter for class com.couchsurfing.mobile.c could not be loaded. Please ensure that code generation was run for this module.
    at dagger.internal.h.a(FailoverLoader.java:45)
    at dagger.internal.h.a(FailoverLoader.java:40)
    at dagger.internal.q.b(Memoizer.java:58)
    at dagger.internal.g.a(FailoverLoader.java:57)
    at dagger.internal.s.a(Modules.java:43)
    at dagger.d.a(ObjectGraph.java:174)
    at dagger.c.b(ObjectGraph.java:129)
    at com.couchsurfing.mobile.CsApp.d(CsApp.java:289)
    at com.couchsurfing.mobile.CsApp.onCreate(CsApp.java:103)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4712)
    at android.app.ActivityThread.-wrap1(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5422) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

Which is from my knowledge a dagger setup issue... However if I add in my proguard.cfg the following:

```
-keepnames class * { @butterknife.* <methods>; }
-keepnames class * { @butterknife.* <fields>; }
```

(in the consumer proguard those are set to `keepclasseswithmembernames`). the issue is fixed...

Well, I have no clue why it look like a dagger configuration issue and after reading the documentation of `keepnames` vs `keepclasseswithmembernames` I don't see why `keepclasseswithmembernames` would be an issue. 

I was wondering if anyone can shed some light on what's going on?

build.gradle:

```
...
  compile 'com.squareup.dagger:dagger:1.2.5'
  provided 'com.squareup.dagger:dagger-compiler:1.2.5'

  compile 'com.jakewharton:butterknife:8.1.0'
  apt 'com.jakewharton:butterknife-compiler:8.1.0'
...
```

**Comment by JakeWharton** [comment]
Well I can say that for one, the consumer proguard rules definitely don't guard against obfuscation. As far as I can tell it's impossible to do this with ProGuard so we don't even try.

**Comment by JakeWharton** [comment]
What is `com.couchsurfing.mobile.c`? My guess is that you're not preventing enough things from being renamed for Dagger, and by doing so for Butter Knife you magically fix Dagger as well.

**Comment by niqo01** [comment]
This is where it's confusing. `com.couchsurfing.mobile.c` is a dagger module:
```
@Module(includes = {
    AppModule.PlatformModule.class, DataModule.class
},
    injects = {
        CsApp.class, AccountAuthenticator.class, PlatformReceiver.class,
        PlatformProcessorService.class, InstanceIDService.class, UploadAnalyticsService.class
    },
    library = true)
public class AppModule {

  private final CsApp application;

  public AppModule(final CsApp application) {
    this.application = application;
  }

  @Provides
  @Singleton
  CsApp provideSurfingApplication() {
    return application;
  }
 ...
```

My proguard dagger related
```
# Dagger
-keep class * extends dagger.internal.Binding
-keep class * extends dagger.internal.ModuleAdapter
-keep class * extends dagger.internal.StaticInjection
-dontwarn dagger.internal.codegen.**
-dontwarn com.squareup.javawriter.** 
```

I really don't see how the `@butterknife.* <methods>;` and `@butterknife.* <fields>; ` are related to this module..

**Comment by JakeWharton** [comment]
Are you able to reproduce this in a small sample? Otherwise I'm not sure what action to take here.

**Comment by JakeWharton** [comment]
Any update?
