### ISSUE TITLE
Upgrading from 8.1.0 to 8.2.0 throws NPE when building

### ISSUE THREAD

**Issue by shekibobo** [JakeWharton/butterknife#670]
Using with kotlin 1.0.3 and Dagger 2.5.

When using ButterKnife 8.1.0, I can build and run my project with no problem, but when trying to upgrade to 8.2.0, I get a `NullPointerException`:

<details>
<summary>`Caused by: java.lang.NullPointerException`</summary>
```
	at butterknife.compiler.ButterKnifeProcessor.scanForRClasses(ButterKnifeProcessor.java:1165)
	at butterknife.compiler.ButterKnifeProcessor.findAndParseTargets(ButterKnifeProcessor.java:176)
	at butterknife.compiler.ButterKnifeProcessor.process(ButterKnifeProcessor.java:153)
	at org.jetbrains.kotlin.annotation.AnnotationProcessorWrapper.process(AnnotationProcessorWrapper.kt:115)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 34 more
```
</details>

Module dependencies include:

```gradle
  provided 'org.glassfish:javax.annotation:10.0-b28'
  kaptAndroidTest "com.google.dagger:dagger-compiler:2.5"
  provided "com.google.dagger:dagger-compiler:2.5"
  kapt "com.google.dagger:dagger-compiler:2.5"

  compile "com.google.dagger:dagger:2.5"

  compile 'com.jakewharton:butterknife:8.2.0'
  kapt 'com.jakewharton:butterknife-compiler:8.2.0'
```

My initial upgrade path required Dagger 2.2 -> 2.5, but that would only allow me to get up to ButterKnife 8.1.0.

If you need any more details, I'm happy to provide them.

**Comment by JakeWharton** [comment]
cc @kageiit

**Comment by kageiit** [comment]
@shekibobo does the issue occur if you do not use kotlin as well?

**Comment by kageiit** [comment]
@shekibobo I put up a PR to guard against the issue, but it would be great if you can provide a small sample to repro this issue so we can fix it without losing access to nicer generated code with `R` references
