### ISSUE TITLE
Issue Butterknife 8.2.1

### ISSUE THREAD

**Issue by pawanpandey17** [JakeWharton/butterknife#708]
Gradle:
apply plugin: 'android-apt'
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.example.android"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'META-INF/services/javax.annotation.processing.Processor'
    }
}
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'
    compile 'com.github.erd:android-volley:1.0.0'
    compile 'com.jakewharton:butterknife:8.2.1'
    compile 'com.jakewharton:butterknife-compiler:8.2.1'
    compile 'de.hdodenhof:circleimageview:2.1.0'
    compile 'com.android.support:support-annotations:23.3.0'
}

@BindView(R.id.listview) ListView mListView;
 
   @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.f_profile, container, false);
        ButterKnife.bind(this, getView());
        return view;
    }

f_profile.xml

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    
    <ListView
        android:id="@+id/listview"
        android:padding="@dimen/dime_21px"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"/>
    

</LinearLayout>

ErrorLog:

Caused by: java.lang.IllegalStateException: Required view 'listview' with ID 2131492950 for field 'mListView' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.
                                                       at butterknife.internal.Finder.findRequiredView(Finder.java:62)
                                                       at butterknife.internal.Finder.findRequiredViewAsType(Finder.java:74)
                                                       at com.mgs.android.fragment.ProfileFragment_ViewBinding.<init>(ProfileFragment_ViewBinding.java:20)
                                                       at com.mgs.android.fragment.ProfileFragment_ViewBinder.bind(ProfileFragment_ViewBinder.java:13)
                                                       at com.mgs.android.fragment.ProfileFragment_ViewBinder.bind(ProfileFragment_ViewBinder.java:10)
                                                       at butterknife.ButterKnife.bind(ButterKnife.java:171)
                                                       at com.mgs.android.fragment.ProfileFragment.addProfileHeader(ProfileFragment.java:61)
                                                       at com.mgs.android.fragment.ProfileFragment.onActivityCreated(ProfileFragment.java:54)
                                                       at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1983)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1092)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
                                                       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602)
                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1245)
                                                       at android.app.Activity.performStart(Activity.java:6581)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2523)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2626) 
                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1475

**Comment by JakeWharton** [comment]
Change
```java
ButterKnife.bind(this, getView());
```
to
```java
ButterKnife.bind(this, view);
```

**Comment by pawanpandey-kiwi** [comment]
oh sorry that copy paste error while posting issue here.
I already tried with ButterKnife.bind(this, view);.
 Im getting same crash.

**Comment by JakeWharton** [comment]
Does findViewById work?

**Comment by pawanpandey-kiwi** [comment]
yes it work fine in that case.

**Comment by JakeWharton** [comment]
The generated code is just calling `findViewById` and checking that the result is not null. If one works so should the other.

**Comment by pawanpandey-kiwi** [comment]
The fragment activity extends AppCompactActivity and i uses below things there. 
In activity butterknife works fine but got the issue in case of fragment.
 
Toolbar toolbar = (Toolbar) findViewById(R.id.my_toolbar);
        setSupportActionBar(toolbar);
        adapter = new NavDrawerListAdapter(HomeActivity.this);
        mDrawerList.setAdapter(adapter);
        mDrawerList.setOnItemClickListener(new SlideMenuClickListener());
        mDrawerToggle = new ActionBarDrawerToggle(this, mDrawerLayout,
                R.drawable.ic_launcher, //nav menu toggle icon
                R.string.app_name, // nav drawer open - description for accessibility
                R.string.app_name // nav drawer close - description for accessibility
        ) {
            public void onDrawerClosed(View view) {
//                getActionBar().setTitle(mTitle);
                // calling onPrepareOptionsMenu() to show action bar icons
                invalidateOptionsMenu();
            }

            public void onDrawerOpened(View drawerView) {
//                getActionBar().setTitle(mDrawerTitle);
                // calling onPrepareOptionsMenu() to hide action bar icons
                invalidateOptionsMenu();
            }
        };
        mDrawerLayout.setDrawerListener(mDrawerToggle);

**Comment by pawanpandey-kiwi** [comment]
got the problem im rebinding header view 
private void addProfileHeader() {
        View headerView = getActivity().getLayoutInflater().inflate(R.layout.header_profile, null, false);
       ButterKnife.bind(this, headerView);
        mListView.addHeaderView(headerView, null, false);

    }

How to do that.

**Comment by JakeWharton** [comment]
Use a dedicated object for the header

**Comment by pawanpandey-kiwi** [comment]
thanku very much sir for your support.
