### ISSUE TITLE
IllegalArgumentException with Jack, Android Gradle Plugin v2.2.0-beta2 & Butterknife v8.2.1

### ISSUE THREAD

**Issue by arcao** [JakeWharton/butterknife#712]
Hi Jake,

I tried to switch one of my project from `Java` to `Jack / Jill` tool-chain, but I stuck on this compilation error:

```
17:52:54.632 [ERROR] [org.gradle.BuildExceptionReporter] 
17:52:54.632 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
17:52:54.632 [ERROR] [org.gradle.BuildExceptionReporter] 
17:52:54.632 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
17:52:54.632 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':transformJackWithJackForDebug'.
17:52:54.632 [ERROR] [org.gradle.BuildExceptionReporter] > java.lang.AssertionError: java.lang.IllegalArgumentException
17:52:54.633 [ERROR] [org.gradle.BuildExceptionReporter] 
17:52:54.633 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
17:52:54.633 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':transformJackWithJackForDebug'.
17:52:54.633 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
17:52:54.633 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
17:52:54.633 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
17:52:54.634 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
17:52:54.634 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
17:52:54.634 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
17:52:54.634 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
17:52:54.634 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
17:52:54.634 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
17:52:54.634 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
17:52:54.634 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
17:52:54.634 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
17:52:54.635 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
17:52:54.635 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
17:52:54.635 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
17:52:54.635 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.RuntimeException: java.lang.AssertionError: java.lang.IllegalArgumentException
17:52:54.635 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.api.v01.impl.Api01ConfigImpl$Api01CompilationTaskImpl.run(Api01ConfigImpl.java:126)
17:52:54.635 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.builder.core.AndroidBuilder.convertByteCodeUsingJackApis(AndroidBuilder.java:1842)
17:52:54.635 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.builder.core.AndroidBuilder.convertByteCodeUsingJack(AndroidBuilder.java:1669)
17:52:54.635 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.build.gradle.internal.transforms.JackTransform.runJack(JackTransform.java:221)
17:52:54.635 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.build.gradle.internal.transforms.JackTransform.transform(JackTransform.java:195)
17:52:54.635 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:178)
17:52:54.636 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:174)
17:52:54.636 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
17:52:54.636 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:173)
17:52:54.636 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
17:52:54.636 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
17:52:54.636 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
17:52:54.636 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
17:52:54.636 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
17:52:54.636 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
17:52:54.636 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
17:52:54.636 [ERROR] [org.gradle.BuildExceptionReporter] 	... 14 more
17:52:54.636 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.AssertionError: java.lang.IllegalArgumentException
17:52:54.636 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.frontend.java.JackBatchCompiler.performCompilation(JackBatchCompiler.java:226)
17:52:54.636 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1712)
17:52:54.636 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.frontend.java.JackBatchCompiler.compile(JackBatchCompiler.java:188)
17:52:54.637 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.Jack.buildSession(Jack.java:977)
17:52:54.637 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.Jack.run(Jack.java:496)
17:52:54.637 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.api.v01.impl.Api01ConfigImpl$Api01CompilationTaskImpl.run(Api01ConfigImpl.java:102)
17:52:54.637 [ERROR] [org.gradle.BuildExceptionReporter] 	... 29 more
17:52:54.637 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.IllegalArgumentException
17:52:54.637 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.source.util.Trees.instance(Trees.java:76)
17:52:54.637 [ERROR] [org.gradle.BuildExceptionReporter] 	at butterknife.compiler.ButterKnifeProcessor.init(ButterKnifeProcessor.java:123)
17:52:54.637 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.eclipse.jdt.internal.compiler.apt.dispatch.BatchAnnotationProcessorManager.discoverNextProcessor(BatchAnnotationProcessorManager.java:157)
17:52:54.637 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:116)
17:52:54.637 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
17:52:54.637 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:909)
17:52:54.637 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:434)
17:52:54.637 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.frontend.java.JackBatchCompiler.performCompilation(JackBatchCompiler.java:223)
17:52:54.637 [ERROR] [org.gradle.BuildExceptionReporter] 	... 34 more
17:52:54.637 [ERROR] [org.gradle.BuildExceptionReporter] 
17:52:54.637 [LIFECYCLE] [org.gradle.BuildResultLogger] 
17:52:54.638 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
```

It looks like something is wrong with `Jack annotation processor`, when the same project works OK with `apt`. Later I found commit with fix e78ee8dfbc5d9d4a9107ec80bc4d47fb9a620393 where this exception is ignored and `scanForRClasses` method body is skipped. I didn't try this new fix yet so I have a question if this fix will really work or whereas I have to create an issue in [AOSP - Issue Tracker](http://b.android.com)?

**Comment by arcao** [comment]
Ugh! Sorry for issue duplication, it seems the discussion is already in issue #673. I am closing this issue.
