### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.setLayoutManager(android.support.v7.widget.RecyclerView$LayoutManager)' on a null object reference

### ISSUE THREAD

**Issue by xiaojw123** [JakeWharton/butterknife#753]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.setLayoutManager(android.support.v7.widget.RecyclerView$LayoutManager)' on a null object reference
	at com.lalocal.lalocal.activity.SearchActivity$SearchCallBack.onGetSearchResult(SearchActivity.java:296)
	at com.lalocal.lalocal.net.ContentLoader$ContentResponse.responseGetSearchResult(ContentLoader.java:1474)
	at com.lalocal.lalocal.net.ContentLoader$ContentResponse.onResponse(ContentLoader.java:1111)
	at com.lalocal.lalocal.net.ContentLoader$ContentResponse.onResponse(ContentLoader.java:936)
	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:60)
	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:1)
	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5438)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by xiaojw123** [comment]
This kind of problem will happen by accident

**Comment by JakeWharton** [comment]
This is not a problem with ButterKnife. Either check for null or don't interact with your view before or after it's bound.

**Comment by SoftgenAndoird** [comment]
Is there anyway to know whether the views has been bounded or not
@JakeWharton Thanks in advance

**Comment by baati** [comment]
Make sure you add the line butterknife.bind in your oncreate

**Comment by ajaypro** [comment]
in onCreate() and onCreateView() is where you make the calls to inflate the layouts, so interacting before the the methods finishes would end in nullpointerexception. 

Better handle it in onStart() or  onResume()

**Comment by amrudesh1** [comment]
dont forget to add ButterKnife.bind(this) in the Oncreate of the activity

**Comment by nadirdpointgroup** [comment]
> in onCreate() and onCreateView() is where you make the calls to inflate the layouts, so interacting before the the methods finishes would end in nullpointerexception.
> 
> Better handle it in onStart() or onResume()

I love you my friend

**Comment by robertocarlosmedina** [comment]
> in onCreate() and onCreateView() is where you make the calls to inflate the layouts, so interacting before the the methods finishes would end in nullpointerexception.
> 
> Better handle it in onStart() or onResume()

Thanks for this solution.
