### ISSUE TITLE
java.lang.IncompatibleClassChangeError: class com.google.auto.common.MoreTypes$1 has interface com.google.common.base.Equivalence as super class

### ISSUE THREAD

**Issue by gzsword** [JakeWharton/butterknife#757]
We use "Butterknife " and "androidannotations " in our project in the same time (We will remove “androidannotations ” In the future, but not now,  because it is a big project)

When we "Sync project with gradle files",  it build successfully,  but Run "app", it show us the following error message:

**（> java.lang.IncompatibleClassChangeError: class com.google.auto.common.MoreTypes$1 has interface com.google.common.base.Equivalence as super class）**

gradle log：

```
17:59:04.762 [ERROR] [org.gradle.BuildExceptionReporter] 
17:59:04.763 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
17:59:04.763 [ERROR] [org.gradle.BuildExceptionReporter] 
17:59:04.763 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
17:59:04.763 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':app:compileMidea_meixin_testDebugJavaWithJavac'.
17:59:04.763 [ERROR] [org.gradle.BuildExceptionReporter] > java.lang.IncompatibleClassChangeError: class com.google.auto.common.MoreTypes$1 has interface com.google.common.base.Equivalence as super class
17:59:04.763 [ERROR] [org.gradle.BuildExceptionReporter] 
17:59:04.763 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
17:59:04.764 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileMidea_meixin_testDebugJavaWithJavac'.
17:59:04.764 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
17:59:04.764 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
17:59:04.764 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
17:59:04.764 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
17:59:04.764 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
17:59:04.764 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
17:59:04.764 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
17:59:04.765 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
17:59:04.765 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
17:59:04.765 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
17:59:04.765 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
17:59:04.766 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
17:59:04.766 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
17:59:04.766 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.ParallelTaskPlanExecutor.process(ParallelTaskPlanExecutor.java:47)
17:59:04.766 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
17:59:04.766 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
17:59:04.766 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
17:59:04.766 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
17:59:04.766 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
17:59:04.766 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
17:59:04.767 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
17:59:04.767 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
17:59:04.767 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
17:59:04.767 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.Factories$1.create(Factories.java:22)
17:59:04.767 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
17:59:04.767 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
17:59:04.767 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
17:59:04.767 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
17:59:04.767 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
17:59:04.767 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
17:59:04.767 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
17:59:04.768 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
17:59:04.768 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
17:59:04.768 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
17:59:04.768 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
17:59:04.768 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:46)
17:59:04.768 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
17:59:04.768 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:58)
17:59:04.768 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
17:59:04.768 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
17:59:04.768 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
17:59:04.768 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
17:59:04.768 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
17:59:04.769 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
17:59:04.769 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
17:59:04.769 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
17:59:04.769 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
17:59:04.769 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
17:59:04.769 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
17:59:04.769 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
17:59:04.769 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
17:59:04.769 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
17:59:04.769 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
17:59:04.769 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
17:59:04.769 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.util.Swapper.swap(Swapper.java:38)
17:59:04.770 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
17:59:04.770 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
17:59:04.770 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
17:59:04.770 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
17:59:04.770 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
17:59:04.770 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
17:59:04.770 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
17:59:04.770 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
17:59:04.770 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
17:59:04.770 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
17:59:04.771 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
17:59:04.771 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
17:59:04.771 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
17:59:04.771 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:237)
17:59:04.771 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
17:59:04.771 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
17:59:04.771 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.RuntimeException: java.lang.IncompatibleClassChangeError: class com.google.auto.common.MoreTypes$1 has interface com.google.common.base.Equivalence as super class
17:59:04.771 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.main.Main.compile(Main.java:553)
17:59:04.771 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
17:59:04.771 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
17:59:04.771 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:46)
17:59:04.771 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
17:59:04.772 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
17:59:04.772 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
17:59:04.772 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
17:59:04.772 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
17:59:04.772 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
17:59:04.772 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:163)
17:59:04.772 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:145)
17:59:04.772 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
17:59:04.772 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
17:59:04.772 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
17:59:04.772 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
17:59:04.773 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
17:59:04.773 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
17:59:04.773 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
17:59:04.773 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
17:59:04.773 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
17:59:04.773 [ERROR] [org.gradle.BuildExceptionReporter] 	... 70 more
17:59:04.773 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.IncompatibleClassChangeError: class com.google.auto.common.MoreTypes$1 has interface com.google.common.base.Equivalence as super class
17:59:04.773 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.google.auto.common.MoreTypes.<clinit>(MoreTypes.java:71)
17:59:04.773 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.google.auto.common.SuperficialValidation$3.visitInt(SuperficialValidation.java:267)
17:59:04.773 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.google.auto.common.SuperficialValidation$3.visitInt(SuperficialValidation.java:199)
17:59:04.773 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.code.Attribute$Constant.accept(Attribute.java:93)
17:59:04.773 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.google.auto.common.SuperficialValidation.validateAnnotationValue(SuperficialValidation.java:281)
17:59:04.773 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.google.auto.common.SuperficialValidation.validateAnnotationValues(SuperficialValidation.java:191)
17:59:04.774 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.google.auto.common.SuperficialValidation.validateAnnotation(SuperficialValidation.java:181)
17:59:04.774 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.google.auto.common.SuperficialValidation.validateAnnotations(SuperficialValidation.java:173)
17:59:04.774 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.google.auto.common.SuperficialValidation.isValidBaseElement(SuperficialValidation.java:102)
17:59:04.774 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.google.auto.common.SuperficialValidation.access$100(SuperficialValidation.java:48)
17:59:04.774 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.google.auto.common.SuperficialValidation$1.visitVariable(SuperficialValidation.java:73)
17:59:04.774 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.google.auto.common.SuperficialValidation$1.visitVariable(SuperficialValidation.java:59)
17:59:04.774 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.code.Symbol$VarSymbol.accept(Symbol.java:1237)
17:59:04.774 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.google.auto.common.SuperficialValidation.validateElement(SuperficialValidation.java:98)
17:59:04.774 [ERROR] [org.gradle.BuildExceptionReporter] 	at butterknife.compiler.ButterKnifeProcessor.findAndParseTargets(ButterKnifeProcessor.java:262)
17:59:04.774 [ERROR] [org.gradle.BuildExceptionReporter] 	at butterknife.compiler.ButterKnifeProcessor.process(ButterKnifeProcessor.java:157)
17:59:04.774 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
17:59:04.774 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
17:59:04.775 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
17:59:04.775 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
17:59:04.775 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
17:59:04.775 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
17:59:04.775 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
17:59:04.775 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.main.Main.compile(Main.java:523)
17:59:04.775 [ERROR] [org.gradle.BuildExceptionReporter] 	... 90 more
17:59:04.775 [ERROR] [org.gradle.BuildExceptionReporter] 
```

**app build gradle**

```
apply from: "config.gradle"

buildscript {
    repositories {
       mavenCentral()
        jcenter {
            url project.JCENTER_REPOSITORY_URL
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}

allprojects {
    repositories {
        mavenCentral()
        jcenter {
            url project.JCENTER_REPOSITORY_URL
        }
    }
//    configurations.all {
//        resolutionStrategy.cacheChangingModulesFor 1, 'seconds'
//    }
}
```

**app build gradle**

```
apt {
    arguments {
        androidManifestFile variant.outputs[0]?.processResources?.manifestFile
        resourcePackageName android.defaultConfig.applicationId
        trace true
        logConsoleAppender true
    }
}

configurations.all {
    resolutionStrategy {
        force "com.android.support:support-annotations:23.1.1"
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile project(':libraries:commonaar')

    //compile project(':libraries:emojicon')
    compile project(':libraries:GNetTangSDKUI')
    compile project(':libraries:filepicker')
    compile 'org.springframework.android:spring-android-core:1.0.1.RELEASE'
    compile 'org.springframework.android:spring-android-rest-template:1.0.1.RELEASE'
    compile files('libs/org.apache.http.legacy.jar')
    compile 'com.android.support:support-v4:23.4.0'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:design:23.4.0'
    compile 'com.android.support:recyclerview-v7:23.4.0'
    compile 'com.android.support:gridlayout-v7:23.4.0'
    compile 'com.android.support:cardview-v7:23.4.0'
    compile 'org.greenrobot:eventbus:3.0.0'
    compile 'com.google.code.gson:gson:2.7'
    compile 'com.afollestad.material-dialogs:core:0.8.5.9'
    compile 'com.android.support:multidex:1.0.1'
    apt "org.androidannotations:androidannotations:4.0.0"
    compile 'org.androidannotations:androidannotations-api:4.0.0'
    apt 'org.androidannotations:rest-spring:4.0.0'
    compile 'org.androidannotations:rest-spring-api:4.0.0'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.squareup.okhttp3:okhttp:3.4.0'
    compile 'jp.wasabeef:glide-transformations:2.0.1'
    compile 'com.daasuu:BubbleLayout:1.1.1'
    // If you want to use the GPU Filters
    compile 'jp.co.cyberagent.android.gpuimage:gpuimage-library:1.3.0'
    compile 'com.bigkoo:pickerview:2.1.1'
    compile 'com.jakewharton:butterknife:8.4.0'
    apt 'com.jakewharton:butterknife-compiler:8.4.0'
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.4.0'
//    compile 'com.squareup.retrofit2:adapter-rxjava:2.1.0'
    compile 'com.jakewharton.retrofit:retrofit2-rxjava2-adapter:1.0.0-RC2'

    compile 'com.jakewharton:butterknife:8.4.0'
    apt 'com.jakewharton:butterknife-compiler:8.4.0'
}
```

**Please help us, thank you**

**Comment by JakeWharton** [comment]
Yeah this isn't a Butter Knife problem and we can't do anything about it. Looks like Gradle is resolving a different version of Google's auto/common project based on your dependencies which is causing the error. You can try using a resolution strategy similar to what you're doing with the support library to force it to the version Butter Knife expects. Otherwise my guess is Android Annotations is using a really old version and needs to update.
