### ISSUE TITLE
java.lang.RuntimeException: Unable to find binding constructor for customview

### ISSUE THREAD

**Issue by mavisli** [JakeWharton/butterknife#778]
I meet this problem on SM-G900F which android version is 5.0. It happened on many custom views.
Do u have any ideas about this?

Fatal Exception: java.lang.RuntimeException: Unable to find binding constructor for com.zhiliaoapp.musically.customview.notifycationview.NotificationLive
       at butterknife.ButterKnife.findBindingConstructorForClass(SourceFile:237)
       at butterknife.ButterKnife.createBinding(SourceFile:191)
       at butterknife.ButterKnife.bind(SourceFile:135)
       at com.zhiliaoapp.musically.customview.notifycationview.NotificationLive.initViews(SourceFile:56)
       at com.zhiliaoapp.musically.customview.notifycationview.NotificationLive.(SourceFile:40)
       at com.zhiliaoapp.musically.adapter.MessageList_ListViewAdapter.initializeItemView(SourceFile:177)
       at com.zhiliaoapp.musically.adapter.MessageList_ListViewAdapter.getView(SourceFile:121)
       at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:232)
       at android.widget.AbsListView.obtainView(AbsListView.java:2842)
       at android.widget.ListView.makeAndAddView(ListView.java:1884)
       at android.widget.ListView.fillSpecific(ListView.java:1364)
       at android.widget.ListView.layoutChildren(ListView.java:1671)
       at android.widget.AbsListView.onLayout(AbsListView.java:2632)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2102)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1956)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1865)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.support.v4.view.ViewPager.onLayout(SourceFile:1695)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2102)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1956)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1865)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2308)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2021)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1180)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6558)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
       at android.view.Choreographer.doCallbacks(Choreographer.java:590)
       at android.view.Choreographer.doFrame(Choreographer.java:560)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5834)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
Caused by java.lang.NoSuchMethodException: <init> [class com.zhiliaoapp.musically.customview.notifycationview.NotificationLive, class android.view.View]
       at java.lang.Class.getConstructor(Class.java:531)
       at java.lang.Class.getConstructor(Class.java:495)
       at butterknife.ButterKnife.findBindingConstructorForClass(SourceFile:231)
       at butterknife.ButterKnife.createBinding(SourceFile:191)
       at butterknife.ButterKnife.bind(SourceFile:135)
       at com.zhiliaoapp.musically.customview.notifycationview.NotificationLive.initViews(SourceFile:56)
       at com.zhiliaoapp.musically.customview.notifycationview.NotificationLive.(SourceFile:40)
       at com.zhiliaoapp.musically.adapter.MessageList_ListViewAdapter.initializeItemView(SourceFile:177)
       at com.zhiliaoapp.musically.adapter.MessageList_ListViewAdapter.getView(SourceFile:121)
       at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:232)
       at android.widget.AbsListView.obtainView(AbsListView.java:2842)
       at android.widget.ListView.makeAndAddView(ListView.java:1884)
       at android.widget.ListView.fillSpecific(ListView.java:1364)
       at android.widget.ListView.layoutChildren(ListView.java:1671)
       at android.widget.AbsListView.onLayout(AbsListView.java:2632)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2102)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1956)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1865)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.support.v4.view.ViewPager.onLayout(SourceFile:1695)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2102)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1956)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1865)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2308)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2021)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1180)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6558)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
       at android.view.Choreographer.doCallbacks(Choreographer.java:590)
       at android.view.Choreographer.doFrame(Choreographer.java:560)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5834)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)

**Comment by JakeWharton** [comment]
What does the `NotificationLive_ViewBinding` class look like?

**Comment by mavisli** [comment]
According to our fabric dashboard, 
<img width="1013" alt="2016-10-21 11 08 28" src="https://cloud.githubusercontent.com/assets/3723407/19585410/cd695138-977e-11e6-8357-e8833a9f347a.png">


Generated NotificationLive_ViewBinding code as below:

     public class NotificationLive_ViewBinding<T extends NotificationLive> implements Unbinder {
                protected T target;

                @UiThread
                 public NotificationLive_ViewBinding(T target, View source) {
                  this.target = target;

                 target.mSdvMessageUserAvatar = Utils.findRequiredViewAsType(source, R.id.message_user_icon, "field 'mSdvMessageUserAvatar'", SimpleDraweeView.class);
                 target.mIvUserFeatured = Utils.findRequiredViewAsType(source, R.id.user_featured, "field 'mIvUserFeatured'", ImageView.class);
                 target.mTvLiveAnchorName = Utils.findRequiredViewAsType(source, R.id.live_anchor_name, "field 'mTvLiveAnchorName'", AvenirTextView.class);
                 target.mTvLiveDesc = Utils.findRequiredViewAsType(source, R.id.message_live_desc, "field 'mTvLiveDesc'", AvenirTextView.class);
                 target.mLayoutAvatar = Utils.findRequiredViewAsType(source, R.id.layout_user_avatar, "field 'mLayoutAvatar'", ViewGroup.class);
  }

                 @Override
                 @CallSuper
                public void unbind() {
                    T target = this.target;
                    if (target == null) throw new IllegalStateException("Bindings already cleared.");

                    target.mSdvMessageUserAvatar = null;
                    target.mIvUserFeatured = null;
                    target.mTvLiveAnchorName = null;
                    target.mTvLiveDesc = null;
                    target.mLayoutAvatar = null;

                    this.target = null;
        }
}

**Comment by JakeWharton** [comment]
That's really weird. The constructor is there and the type types match. I'm not sure how to move forward here without a means to reproduce this.

**Comment by naveenOnarayanan** [comment]
Same issue happening with us on the Sm-G900f device.

**Comment by lyahdav** [comment]
Same issue on a sm-g900m device.
OS Version: 5.0
Is Rooted: false
Play Services Version: 10.0.84 (238-137749526)

No idea how to debug. It's happening to a user of ours so we don't have access to the device to investigate further.

**Comment by hzsweers** [comment]
We interestingly just saw this pop up as well

**Comment by yendangn** [comment]
Same with me

**Comment by thenickreynolds** [comment]
I'm seeing the same issue at Airbnb - our bug reporting framework has recorded a few hundred reports. I don't have a specific repro but I do see it's only occurring for Samsung phones SM-G900F and SM-G900M with Android 5.0.

Let me know if you want any more info.

**Comment by rorpage** [comment]
I just had this happen to me and a clean and rebuild of my project solved it. I had upgraded a bunch of things including Butterknife.

**Comment by JakeWharton** [comment]
The library is generating the correct code and the reflection is correct so the problem isn't in the library. That said, if someone wants to improve the library in a way that avoids this device/platform-specific bug that's fine, but there's no inherent issue with the library.

**Comment by ramaniajay146** [comment]
java.lang.RuntimeException: Unable to find binding constructor for followers.tracker.analyzer.uiActivities.LostFollower$FollowCommonAdptr$ViewHolder
        at butterknife.ButterKnife.findBindingConstructorForClass(ButterKnife.java:210)

 public ViewHolder(View view) {
                super(view);
                ButterKnife.bind((Object) this, view);
            }
![Screenshot_50](https://user-images.githubusercontent.com/87351525/163326070-3904dd42-8e77-4cba-b39c-81de016c98a2.png)
