### ISSUE TITLE
i got an error in android 7.0

### ISSUE THREAD

**Issue by q7w8e9123456** [JakeWharton/butterknife#781]
When I use the listview will slip when a mistake
get object is null point error

my list item has 8 objects

error code:
									E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.spiderweb.spidercard, PID: 28046
                                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                                                                              at com.spiderweb.spidercard.widgets.ContactSection.setTitle(ContactSection.java:49)
                                                                              at com.spiderweb.spidercard.fragment.contacts.CardContactAdapter.setSectionData(CardContactAdapter.java:155)
                                                                              at com.spiderweb.spidercard.fragment.contacts.CardContactAdapter.getView(CardContactAdapter.java:71)
                                                                              at android.widget.AbsListView.obtainView(AbsListView.java:2362)
                                                                              at android.widget.ListView.makeAndAddView(ListView.java:1970)
                                                                              at android.widget.ListView.fillDown(ListView.java:704)
                                                                              at android.widget.ListView.fillGap(ListView.java:668)
                                                                              at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5185)
                                                                              at android.widget.ListView.trackMotionScroll(ListView.java:1889)
                                                                              at android.widget.AbsListView.scrollIfNeeded(AbsListView.java:3567)
                                                                              at android.widget.AbsListView.onTouchMove(AbsListView.java:3976)
                                                                              at android.widget.AbsListView.onTouchEvent(AbsListView.java:3801)
                                                                              at android.view.View.dispatchTouchEvent(View.java:9942)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2663)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
                                                                              at com.spiderweb.spidercard.widgets.PinnedSectionListView.dispatchTouchEvent(PinnedSectionListView.java:481)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                              at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:411)
                                                                              at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
                                                                              at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
                                                                              at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                              at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:373)
                                                                              at android.view.View.dispatchPointerEvent(View.java:10162)
                                                                              at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4434)
                                                                              at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
                                                                              at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
                                                                              at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
                                                                              at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3995)

									 E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
                                                                              at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4052)
                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
                                                                              at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
                                                                              at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
                                                                              at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
                                                                              at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6210)
                                                                              at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6184)
                                                                              at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6145)
                                                                              at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6313)
                                                                              at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                              at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                              at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                              at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6284)
                                                                              at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6336)
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                              at android.view.Choreographer.doFrame(Choreographer.java:613)
                                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by JakeWharton** [comment]
The view is `null`. You forgot to call `bind()` or marked the view as `@Nullable` (aka optional) and it wasn't present in the layout.

**Comment by q7w8e9123456** [comment]
I found this error because I in the listitem onDetachedFromWindow call unbinder.unbind ();
So I do not need to call this method in listitem ???

@Override
     Protected void onDetachedFromWindow () {
         Unbinder.unbind ();
         Super.onDetachedFromWindow ();
     }}
