### ISSUE TITLE
cannot add an action twice: Generate Butterknife Injections (Plugin for generating ButterKnife injections from selected layout XMLs in activities/fragments/adapters)

### ISSUE THREAD

**Issue by fengshenyanyi** [JakeWharton/butterknife#805]
java.lang.IllegalArgumentException: cannot add an action twice: Generate Butterknife Injections (Plugin for generating ButterKnife injections from selected layout XMLs in activities/fragments/adapters)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.addAction(DefaultActionGroup.java:151)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.addAction(DefaultActionGroup.java:137)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.add(DefaultActionGroup.java:108)
	at com.intellij.codeInsight.generation.actions.GenerateAction.wrapGroup(GenerateAction.java:90)
	at com.intellij.codeInsight.generation.actions.GenerateAction.actionPerformed(GenerateAction.java:40)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:485)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

使用插件之后，generate 都不能用了 ？？急求解

**Comment by fengshenyanyi** [comment]
我把 ButterKnife 插件取消了 generate 就能用了 但是 右键generate 没有 butterknife的选项

**Comment by JakeWharton** [comment]
Please file on https://github.com/avast/android-butterknife-zelezny

**Comment by kazimdsaidul** [comment]
IllegalArgumentException: cannot add an action twice: Generate Butterknife Injections (Plugin for generating ButterKnife injections from selected layout XMLs in activities/fragments/adapters)

**Comment by niroj08** [comment]
@fengshenyanyi  @kazimdsaidul 
Go to plugins, search for Android Butterknife Zelenzy and other butterknife plugins, uninstall it. it will fix the issue

if you want them back, do install again.
