### ISSUE TITLE
NullPointerException: got NPE after ButterKnife.bind(this, itemView) in adapter

### ISSUE THREAD

**Issue by zezekalo** [JakeWharton/butterknife#806]
I`ve got NPE in adapter:

`java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setVisibility(int)' on a null object reference
                                                                         at test.android.adapters.swiperemove.SwipeRemoveAdapter.onBindViewHolder(SwipeRemoveAdapter.java:73)
                                                                         at test.android.adapters.AccountsAdapter.onBindViewHolder(AccountsAdapter.java:65)
                                                                         at test.android.adapters.AccountsAdapter.onBindViewHolder(AccountsAdapter.java:32)
                                                                         at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5822)
                                                                         at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5855)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5091)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4967)
                                                                         at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                         at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                                         at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                         at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3124)
                                                                         at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
                                                                         at android.view.View.layout(View.java:16672)`

I have main ViewHolder:

`public class SwipeRemoveViewHolder extends RecyclerView.ViewHolder {

	@BindView(R.id.undo_button) Button undoButton;
	@BindView(R.id.del_status) TextView delStatus;

	public SwipeRemoveViewHolder(View itemView) {
		super(itemView);
	}

	@Override
	public String toString() {
		final StringBuffer sb = new StringBuffer("SwipeRemoveViewHolder{");
		sb.append("undoButton=").append(undoButton);
		sb.append(", delStatus=").append(delStatus);
		sb.append('}');
		return sb.toString();
	}
}`

and inheritor AccountItemHolder:

`	public class AccountItemHolder extends SwipeRemoveViewHolder implements View.OnClickListener, ChoiceModeController {

		@BindView(R.id.account_heading) TextView name;
		@BindView(R.id.account_subheading) TextView username;
		@BindView(R.id.account_icon) ImageView avatar;
		@BindView(R.id.account_status) CheckBox status;
		@BindView(R.id.account_container) ViewGroup container;

		private Context context;
		private SwipeRemoveChoiceCapableAdapter adapter;

		public AccountItemHolder(SwipeRemoveChoiceCapableAdapter adapter, View itemView) {
			super(itemView);
			ButterKnife.bind(this, itemView);
			this.context = itemView.getContext();
			this.adapter = adapter;
			itemView.setOnClickListener(this);
		}
}
...
`

AccountsAdapter 

`
	@Override
	public void onBindViewHolder(AccountItemHolder accountHolder, int position) {
		logger.verbose("AccountsAdapter: onBindViewHolder: accountHolder - " + accountHolder);
		super.onBindViewHolder(accountHolder, position);
...
`

and logs before crash
`11-17 17:45:39.447 27499-27499/test.android V/MyLogger: AccountsAdapter: onBindViewHolder: accountHolder - AccountItemHolder{super=SwipeRemoveViewHolder{**undoButton=null**, **delStatus=null**}; name=android.support.v7.widget.AppCompatTextView{20a0c591 V.ED.... ......I. 0,0-0,0 #7f0c0070 app:id/account_heading}, username=android.support.v7.widget.AppCompatTextView{3fcc7cf6 V.ED.... ......I. 0,0-0,0 #7f0c0071 app:id/account_subheading}, avatar=android.support.v7.widget.AppCompatImageView{146858f7 V.ED.... ......I. 0,0-0,0 #7f0c006e app:id/account_icon}, status=android.support.v7.widget.AppCompatCheckBox{1935364 VFED.... ......I. 0,0-0,0 #7f0c006f app:id/account_status}, container=android.widget.RelativeLayout{327b29cd V.E..... ......I. 0,0-0,0 #7f0c006d app:id/account_container}, context=studyladder.android.activities.MainActivity@179aaa7}`

I wounder why some views are null(undoButton, delStatus) but others are not (f.e. name) after Butterknife bindind in constractor AccountItemHolder? What did I wrong?

**Comment by zezekalo** [comment]
This issue is not permanent, after rebuilt application often I didn't caught this bug.

**Comment by JakeWharton** [comment]
Are you using instant run?

**Comment by zezekalo** [comment]
Yes, I am.

**Comment by JakeWharton** [comment]
Instant run is the problem. You should file a bug on http://b.android.com about it. It is impossible for this to happen using normal build tooling.
