### ISSUE TITLE
 java.lang.NullPointerException: Cannot invoke method replaceAll() on null object ButterKnifePlugin.groovy:32

### ISSUE THREAD

**Issue by manjunathc23** [JakeWharton/butterknife#842]
Compilation error when I do split APK. 

```
:app:processFullArmeabi-v7aAutomationManifest
:app:processFullArmeabi-v7aAutomationResources FAILED
:myntra:compileRetrolambdaDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processFullArmeabi-v7aAutomationResources'.
> Cannot invoke method replaceAll() on null object

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processFullArmeabi-v7aAutomationResources'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.NullPointerException: Cannot invoke method replaceAll() on null object
        at butterknife.plugin.ButterKnifePlugin$_apply_closure1$_closure2$_closure3$_closure4.doCall(ButterKnifePlugin.groovy:32)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:590)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:571)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more


BUILD FAILED

Total time: 8.308 secs

```
Please help @JakeWharton 

Repo : https://github.com/zetaapps/zeta
Branch : MC_MYNTRA

Thanks!
Manju

**Comment by manjunathc23** [comment]
Any help here please ? @JakeWharton

**Comment by sapphirejade** [comment]
I encounter the same problem with v8.5.1 when trying to split APK like following:
```gradle
splits {
    density {
        enable true
	reset()
	include "xxhdpi"
    }
}
```
However, if I change to v8.6.0, https://github.com/JakeWharton/butterknife/issues/961 will happen.


**Here is how I fix it.**
1. In _Project build.gradle_, only use _jcenter_ and _com.android.tools.build:gradle:2.3.2_
```gradle
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.2'
    }
}
```
2. In _Module(app) build.grade_, 
- Remove _apply plugin: 'com.jakewharton.butterknife'_
```gradle
  apply plugin: 'com.android.application'
  // apply plugin: 'com.jakewharton.butterknife'
```
- Remove _buildscript_ 
```gradle
// buildscript {		
//     repositories {		
//         jcenter()		
//         mavenCentral()		
//     }		
//     dependencies {		
//         classpath 'com.jakewharton:butterknife-gradle-plugin:8.6.0'		
//     }		
// }
```
- Use dependencies like what @JakeWharton said in https://github.com/JakeWharton/butterknife#download
```gradle
dependencies {
    compile 'com.jakewharton:butterknife:8.6.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.6.0'
}
```

Hope these information would be helpful.

**Comment by Windymonkeys** [comment]
why remove apply plugin: 'com.jakewharton.butterknife' and  buildscript
