### ISSUE TITLE
Bind Views of AlertDialog in Activity 

### ISSUE THREAD

**Issue by DarpanSolanki** [JakeWharton/butterknife#889]
Hi, I am having an AlertDialog which is opened on click of a RecyclerView ListItem and want to bind the views in the AlertDialog using Butterknife.
For now I am binding the views at class level but it is giving null pointer.

_This is the code snippet_

AlertDialog.Builder builder = new AlertDialog.Builder(this).setCancelable(false);
View detailView=LayoutInflater.from(getApplicationContext()).inflate(R.layout.wallet_statement_item_details_layout,null,false);
        builder.setView(detailView);
        ButterKnife.bind(this,detailView);

Can you tell me how to do it ?

**Comment by JakeWharton** [comment]
What you have is fine. Please provide a full failing sample or test case.

**Comment by DarpanSolanki** [comment]
> PFA the Code

public class TransactionStatementActivity extends DemoBaseActivity implements TransactionStatementIView 
{
    private TransactionStatementPresenter transactionStatementPresenter;
    private GetWalletStatementResponse getWalletStatementResponse;
    private WalletStatementAdapter adapter;
    private LinearLayoutManager layoutManager;

    @Bind(R.id.transaction_list)
    RecyclerView recyclerView;

    @Bind(R.id.main_swipe_refresh_layout)
    SwipeRefreshLayout swipeRefreshLayout;

    @Bind(R.id.statement_details_text)
    TextView statementTextView;

    @Bind(R.id.statement_handle_details)
    TextView statementHandleDetailsTextView;

    @Bind(R.id.statement_details_value)
    TextView statementDetailsValueTextView;

    @Bind(R.id.statement_reference_number_value)
    TextView statementReferenceNumberValueTextView;

    @Bind(R.id.statement_date_value)
    TextView statementDateValueTextView;

    @Bind(R.id.statement_amount_value)
    TextView statementAmountValueTextView;

    @Bind(R.id.statement_total_amount_value)
    TextView statementTotalAmountValueTextView;

    @Bind(R.id.statement_charge_value)
    TextView statementChargeValueTextView;


    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_transaction_statement_layout);
        ButterKnife.bind(this);

        getAppComponent().inject(this);
        transactionStatementPresenter = new TransactionStatementPresenter(service, this);
        transactionStatementPresenter.getTransactionList();
    }

    @Override
    public TransactionStatementActivity getActivityContext() {
        return this;
    }

    @Override
    public void setUIFromResponse() {
        insertDataInUI();
    }

    @Override
    public void showDetailsDialog(int pos) {
        AlertDialog.Builder builder = new AlertDialog.Builder(this).setCancelable(false);
        View detailView = LayoutInflater.from(getApplicationContext()).inflate(R.layout.wallet_statement_item_details_layout, null, false);
        builder.setView(detailView);
        ButterKnife.bind(this, detailView);

        GetWalletStatementResponse.StatementResponse statementResponse = getWalletStatementResponse.getStatementResponnseList().get(pos);

        // Set Values in Details view from response

        builder.setPositiveButton(AppConstants.DISMISS, new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int which) {
                dialog.dismiss();
            }
        });
    }

> PFA the Error Logs.

Caused by: java.lang.RuntimeException: Unable to bind views for in.demo.uba.ui.activities.TransactionStatementActivity
                                                                    at butterknife.ButterKnife.bind(ButterKnife.java:322)
                                                                    at butterknife.ButterKnife.bind(ButterKnife.java:237)
                                                                    at in.demo.uba.ui.activities.TransactionStatementActivity.onCreate(TransactionStatementActivity.java:72)
                                                                    at android.app.Activity.performCreate(Activity.java:6259)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2382)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493) 
                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5459) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                 Caused by: java.lang.IllegalStateException: Required view 'statement_details_text' with ID 2131755576 for field 'statementTextView' was not found. If this view is optional add '@Nullable' annotation.
                                                                    at butterknife.ButterKnife$Finder.findRequiredView(ButterKnife.java:140)
                                                                    at in.demo.uba.ui.activities.TransactionStatementActivity$$ViewBinder.bind(TransactionStatementActivity$$ViewBinder.java:15)
                                                                    at in.demo.uba.ui.activities.TransactionStatementActivity$$ViewBinder.bind(TransactionStatementActivity$$ViewBinder.java:8)
                                                                    at butterknife.ButterKnife.bind(ButterKnife.java:319)
                                                                    at butterknife.ButterKnife.bind(ButterKnife.java:237) 
                                                                    at in.demo.uba.ui.activities.TransactionStatementActivity.onCreate(TransactionStatementActivity.java:72) 
                                                                    at android.app.Activity.performCreate(Activity.java:6259) 
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130) 
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2382) 
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493) 
                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5459) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by JakeWharton** [comment]
You are trying to bind the same object twice to two different view hierarchies. This will never work. Your best bet is to create a view holder-like object for the views that are inside the dialog.

```java
class DialogViews {
  @BindView(R.id.view_in_dialog) TextView tv;
}
```
and pass an instance of that class as the first argument to `bind`.
