### ISSUE TITLE
Release build: Error: Expected resource of type id [ResourceType]

### ISSUE THREAD

**Issue by jsullivan-cambrian** [JakeWharton/butterknife#914]
Debug builds work with no errors. Building for release causes the following error:

```
Error:Premature end of file.
app\build\generated\source\kapt\appRelease\com\_____\____\base\BaseActivity_ViewBinding.java
Error:Error: Expected resource of type id [ResourceType]
```

build.gradle:

```
apply plugin: 'kotlin'
apply plugin: 'kotlin-kapt'

android {
    //...
    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-DEBUG'
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    //...
    compile 'com.jakewharton:butterknife:8.5.1'
    kapt 'com.jakewharton:butterknife-compiler:8.5.1'

    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
}
```

**Comment by JakeWharton** [comment]
What's the generated code look like?

**Comment by jsullivan-cambrian** [comment]
```
public final class BaseActivity_ViewBinding implements Unbinder {
  private BaseActivity target;

  @UiThread
  public BaseActivity_ViewBinding(BaseActivity target) {
    this(target, target.getWindow().getDecorView());
  }

  @UiThread
  public BaseActivity_ViewBinding(BaseActivity target, View source) {
    this.target = target;

    target.toolbar = Utils.findRequiredViewAsType(source, 2131689604, "field 'toolbar'", Toolbar.class);
    target.drawer = Utils.findRequiredViewAsType(source, 2131689602, "field 'drawer'", DrawerLayout.class);
    target.navigationView = Utils.findRequiredViewAsType(source, 2131689605, "field 'navigationView'", NavigationView.class);
    target.container = Utils.findRequiredViewAsType(source, 2131689603, "field 'container'", ViewGroup.class);
  }

  @Override
  public void unbind() {
    BaseActivity target = this.target;
    if (target == null) throw new IllegalStateException("Bindings already cleared.");
    this.target = null;

    target.toolbar = null;
    target.drawer = null;
    target.navigationView = null;
    target.container = null;
  }
}
```

Binds in the activity:

```
@BindView(R.id.toolbar)             lateinit var toolbar: Toolbar
@BindView(R.id.drawer_layout)       lateinit var drawer: DrawerLayout
@BindView(R.id.nav_view)            lateinit var navigationView: NavigationView
@BindView(R.id.controller_container) lateinit var container: ViewGroup
```

And the XML:

```
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="false"
    tools:openDrawer="start">

    <android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.bluelinelabs.conductor.ChangeHandlerFrameLayout
            android:id="@+id/controller_container"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior"
            />

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

        </android.support.v7.widget.Toolbar>

    </android.support.design.widget.CoordinatorLayout>


    <android.support.design.widget.NavigationView
        android:id="@+id/nav_view"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        android:fitsSystemWindows="true"
        app:headerLayout="@layout/header"
        app:menu="@menu/drawer" />

</android.support.v4.widget.DrawerLayout>
```

**Comment by JakeWharton** [comment]
Hmm there should be a `@SuppressWarnings` on that. I'll try to have a look
this week.

**Comment by jsullivan-cambrian** [comment]
I tried suppressing it with this in lint.xml

```
<issue id="ResourceType">
    <!-- Remove this when this is fixed: https://github.com/JakeWharton/butterknife/issues/338 -->
    <ignore path="**/*_ViewBinding.java" />
</issue>
```
It lets the build complete, but then it crashes on launch, presumably due to a null view reference. It's just basically impossible to tell because it's minified.

```03-29 16:04:25.855 23397-23397/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.cambriantech.paintharmonylite, PID: 23397
                                                   java.lang.RuntimeException: Unable to create application com.cambriantech.harmony.base.MyApp: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method a.d.b.d.b, parameter tag
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5406)
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                    Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method a.d.b.d.b, parameter tag
                                                       at com.cambriantech.harmony.base.MyApp$b.a(Unknown Source)
                                                       at b.a.a$b.a(Unknown Source)
                                                       at b.a.a$b.b(Unknown Source)
                                                       at b.a.a$1.b(Unknown Source)
                                                       at b.a.a.b(Unknown Source)
                                                       at com.cambriantech.harmony.a.c.b(Unknown Source)
                                                       at com.cambriantech.harmony.a.c.c(Unknown Source)
                                                       at com.cambriantech.harmony.base.MyApp.onCreate(Unknown Source)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

Mostly I just don't understand why it works in debug but not release. Even enabling minify on debug works without issue.

**Comment by JakeWharton** [comment]
Are you sure that's from Butter Knife? That exception is from a Kotlin
intrinsic which indicates you're passing null to a method whose parameter
is declared as non-null, but Butter Knife wouldn't return you a null view
unless you declared it as @Nullable or @Optional.

**Comment by jsullivan-cambrian** [comment]
I'm not sure. The errors led me here but it's entirely possible that I'm wrong. If that were the case, what would make it behave differently in debug vs release? 

I'll keep investigating,  thanks for the help.

**Comment by JakeWharton** [comment]
Well what method call is that like referring to?

**Comment by jsullivan-cambrian** [comment]
You were right, it was a null issue elsewhere - but it was with Timber which is another of your libraries so I'll go ahead and post it in this thread:

I have basic logging set up like this

    Timber.plant(if (BuildConfig.DEBUG)
            Timber.DebugTree()
        else
            CrashReportingTree())

Which calls this class:


    private inner class CrashReportingTree : Timber.Tree() {
        override fun log(priority: Int, tag: String?, message: String?, throwable: Throwable?) {
            if(tag == null) {
                Log.e("ApplicationCreate", "TAG IS NULL")
                return
            }
            message?.let {
                FirebaseCrash.logcat(priority, tag, message)
                if (priority == Log.ERROR) {
                    val t: Throwable = throwable ?: Exception(message)
                    FirebaseCrash.report(t)
                }
            }

        }
    }

`tag` is never supposed to be null, but apparently it is in certain cases. Basic log messages like these result in a null tag, which from what I can tell from looking at the code and searching around shouldn't be possible:

```
Timber.i("Active project is now " + activeProject.name + " - " + activeProject.projectID)
Timber.d("wheel already created")
```

I can post this issue on the Timber github page if you'd prefer.


If anyone else gets the same error from ButterKnife, just put this into your `lint.xml`, it will fix the problem.

```
<issue id="ResourceType">
    <!-- Remove this when this is fixed: https://github.com/JakeWharton/butterknife/issues/338 -->
    <ignore path="**/*_ViewBinding.java" />
</issue>
```

**Comment by JakeWharton** [comment]
With Timber the tag can absolutely be null if it's not explicitly specified
and the Tree doesn't have any other means of looking it up.

**Comment by jsullivan-cambrian** [comment]
Ah my mistake then, guess I'll have to fix up some of my code. Thanks very much for the help, love your libraries.

**Comment by mnawrott** [comment]
Writing here, since I don't want to create new one. 
I got similar problem, but my builds are not crashing after disabling 'ResourceType' in lintOptions -
 the app is doing just fine.

Generated code:
```
// Generated code from Butter Knife. Do not modify!
package com.example.app;

import android.support.annotation.UiThread;
import android.support.v7.widget.Toolbar;
import android.view.View;
import butterknife.Unbinder;
import butterknife.internal.Utils;
import java.lang.IllegalStateException;
import java.lang.Override;

public final class ExampleActivity_ViewBinding implements Unbinder {
  private ExampleActivity target;

  @UiThread
  public ExampleActivity_ViewBinding(ExampleActivity target) {
    this(target, target.getWindow().getDecorView());
  }

  @UiThread
  public ExampleActivity_ViewBinding(ExampleActivity target, View source) {
    this.target = target;

    target.toolbar = Utils.findRequiredViewAsType(source, 2131558524, "field 'toolbar'", Toolbar.class);
  }

  @Override
  public void unbind() {
    ExampleActivity target = this.target;
    if (target == null) throw new IllegalStateException("Bindings already cleared.");
    this.target = null;

    target.toolbar = null;
  }
}
```
Binding inside activity : 
```
@BindView(R.id.toolbar)
    lateinit var toolbar: Toolbar
```
XML:
```
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/AppTheme.AppBarOverlay">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            app:popupTheme="@style/AppTheme.PopupOverlay" />

    </android.support.design.widget.AppBarLayout>

    <FrameLayout
        android:id="@+id/fragment_frame"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

    </FrameLayout>

</android.support.design.widget.CoordinatorLayout>
```

**Comment by krokyze** [comment]
Yes having the same problem:
"Error: Expected resource of type id [ResourceType] target.badge = Utils.findRequiredViewAsType(source, 2131689615, "field 'badge'", FontTextView.class);"

**Comment by jbir789** [comment]
I am getting the same issue, using a Kotlin view. The linter doesn't fail with ButterKnife 8.5.1.
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
   xmlns:android="http://schemas.android.com/apk/res/android"
   android:layout_width="match_parent"
   android:layout_height="match_parent"
   android:orientation="vertical"
   android:paddingLeft="@dimen/standard_vertical_margin"
   android:paddingRight="@dimen/standard_vertical_margin"
   android:gravity="center_horizontal">

   <Space
      android:layout_width="0dp"
      android:layout_height="0dp"
      android:layout_weight="2" />

   <TextView
      style="@style/TextView.Header"
      android:layout_marginBottom="@dimen/standard_vertical_margin"
      android:text="@string/repair_title" />

   <ImageView
      style="@style/HeaderImage"
      android:layout_marginBottom="@dimen/standard_vertical_margin"
      android:src="@drawable/img_repair_phone" />

   <TextView
      style="@style/TextView.Regular"
      android:layout_marginBottom="@dimen/standard_vertical_margin"
      android:text="@string/repair_text" />

   <Button
      android:id="@+id/repair_button"
      style="@style/Button.Solid"
      android:text="@string/repair_button_hint" />

   <Space
      android:layout_width="0dp"
      android:layout_height="0dp"
      android:layout_weight="3" />

</LinearLayout>
```

Controller (from conductor). Butterknife.bind is called in a base class (using java):
```kt
class RepairController : BaseController {

   constructor(): super()

   constructor(args: Bundle) : super(args)

   override fun inflateView(inflater: LayoutInflater, container: ViewGroup): View {
      return inflater.inflate(R.layout.view_repair, container, false)
   }

   override fun onViewBound(view: View) {
      super.onViewBound(view)
   }

   @OnClick(R.id.repair_button)
   fun repairApp() {
     // do stuff
   }

}
```

and then, when building, the linter fails:
Expected resource of type id
```java
 21     this.target = target;
 22 
 23     View view;
 24     view = Utils.findRequiredView(source, 2131624130, "method 'repairApp'");                        
 25     view2131624130 = view;
 26     view.setOnClickListener(new DebouncingOnClickListener() {
 27       @Override
```
