### ISSUE TITLE
butterKnife RuntimeException: Unable to find binding constructor  NoSuchMethodException: <init> 

### ISSUE THREAD

**Issue by rixtdqqq** [JakeWharton/butterknife#918]
04-03 00:16:32.796 32015-32015/com.example.mvpdemo E/AppCompatResources: Failed to inflate ColorStateList, leaving it to the framework
                                                                         java.lang.RuntimeException: Failed to resolve attribute at index 0
                                                                             at android.content.res.TypedArray.getColor(TypedArray.java:401)
                                                                             at android.support.v7.content.res.AppCompatColorStateListInflater.inflate(AppCompatColorStateListInflater.java:114)
                                                                             at android.support.v7.content.res.AppCompatColorStateListInflater.createFromXmlInner(AppCompatColorStateListInflater.java:88)
                                                                             at android.support.v7.content.res.AppCompatColorStateListInflater.createFromXml(AppCompatColorStateListInflater.java:67)
                                                                             at android.support.v7.content.res.AppCompatResources.inflateColorStateList(AppCompatResources.java:116)
                                                                             at android.support.v7.content.res.AppCompatResources.getColorStateList(AppCompatResources.java:74)
                                                                             at android.support.v7.widget.TintTypedArray.getColorStateList(TintTypedArray.java:136)
                                                                             at android.support.v7.widget.AppCompatTextHelper.onSetTextAppearance(AppCompatTextHelper.java:157)
                                                                             at android.support.v7.widget.AppCompatTextView.setTextAppearance(AppCompatTextView.java:148)
                                                                             at android.support.v4.widget.TextViewCompatGingerbread.setTextAppearance(TextViewCompatGingerbread.java:103)
                                                                             at android.support.v4.widget.TextViewCompat$BaseTextViewCompatImpl.setTextAppearance(TextViewCompat.java:86)
                                                                             at android.support.v4.widget.TextViewCompat.setTextAppearance(TextViewCompat.java:283)
                                                                             at android.support.design.widget.TextInputLayout.setErrorEnabled(TextInputLayout.java:609)
                                                                             at android.support.design.widget.TextInputLayout.<init>(TextInputLayout.java:253)
                                                                             at android.support.design.widget.TextInputLayout.<init>(TextInputLayout.java:183)
                                                                             at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                             at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                             at com.example.mvpdemo.view.fragment.LoginFragment.onCreateView(LoginFragment.java:75)
                                                                             at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                             at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                             at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                             at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                             at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                             at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                             at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                             at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                                             at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                                             at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
                                                                             at android.app.Activity.performStart(Activity.java:5949)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                         	at com.android.internal.os.ZygoteInit.main(ZygoteIn
04-03 00:16:32.825 32015-32015/com.example.mvpdemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.example.mvpdemo, PID: 32015
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.mvpdemo/com.example.mvpdemo.view.activity.LoginActivity}: java.lang.RuntimeException: Unable to find binding constructor for com.example.mvpdemo.view.fragment.LoginFragment
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
                                                                      Caused by: java.lang.RuntimeException: Unable to find binding constructor for com.example.mvpdemo.view.fragment.LoginFragment
                                                                         at butterknife.ButterKnife.findBindingConstructorForClass(ButterKnife.java:237)
                                                                         at butterknife.ButterKnife.createBinding(ButterKnife.java:191)
                                                                         at butterknife.ButterKnife.bind(ButterKnife.java:172)
                                                                         at com.example.mvpdemo.view.base.BaseFragment.onViewCreated(BaseFragment.java:21)
                                                                         at com.example.mvpdemo.view.fragment.LoginFragment.onViewCreated(LoginFragment.java:59)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1314)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                         at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                         at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                         at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                                         at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                                         at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
                                                                         at android.app.Activity.performStart(Activity.java:5949)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:135) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5221) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
                                                                      Caused by: java.lang.NoSuchMethodException: <init> [class com.example.mvpdemo.view.fragment.LoginFragment, class android.view.View]
                                                                         at java.lang.Class.getConstructor(Class.java:531)
                                                                         at java.lang.Class.getConstructor(Class.java:495)
                                                                         at butterknife.ButterKnife.findBindingConstructorForClass(ButterKnife.java:231)
                                                                         at butterknife.ButterKnife.createBinding(ButterKnife.java:191) 
                                                                         at butterknife.ButterKnife.bind(ButterKnife.java:172) 
                                                                         at com.example.mvpdemo.view.base.BaseFragment.onViewCreated(BaseFragment.java:21) 
                                                                         at com.example.mvpdemo.view.fragment.LoginFragment.onViewCreated(LoginFragment.java:59) 
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1314) 
                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528) 
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595) 
                                                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758) 
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363) 
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149) 
                                                                         at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103) 
                                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013) 
                                                                         at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388) 
                                                                         at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607) 
                                                                         at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178) 
                                                                         at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220) 
                                                                         at android.app.Activity.performStart(Activity.java:5949) 
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:135) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5221) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
04-03 00:16:33.129 754-1325/system_process E/ActivityManager: Invalid thumbnail dimensions: 420x420
04-03 00:16:35.630 754-826/system_process E/WifiStateMachine: CMD_START_SCAN : connected mode and no configuration

**Comment by rixtdqqq** [comment]
@Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        ButterKnife.bind(this, view);
    }

when bind, one issue accurs

**Comment by ber4444** [comment]
This seems to be happening on KitKat only. Probably unrelated to butterknife, the error comes from the support library, just search https://android.googlesource.com/platform/frameworks/support/+/9d5f84f/v7/appcompat/src/android/support/v7/widget/ColorStateListUtils.java

**Comment by JakeWharton** [comment]
Can you provide a sample demonstrating the problem?

**Comment by rorpage** [comment]
I just had this happen to me and a clean and rebuild of my project solved it. I had upgraded a bunch of things including Butterknife.
