### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lbutterknife/ButterKnife

### ISSUE THREAD

**Issue by dev-juyoung** [JakeWharton/butterknife#929]
Hello JakeWharton!
I am currently developing a library.
I checked and set the README file to use ButterKnife in my library project.
Before proceeding with full-scale development,
After doing the basic work for testing,
I created an aar file, imported aar into another project, and tried to run it.

However, it displays the same error as the title of the issue.
How can we solve it?

Library Project Source
===

**project level gradle**
```
ext {
    // another code...
    butterknifeVersion = '8.5.1'
}

buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.1'
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.5.1'
    }
}
```

**module level gradle**
```
apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife'

// another code...

dependencies {
    // another code...
    compile "com.jakewharton:butterknife:${butterknifeVersion}"
    annotationProcessor "com.jakewharton:butterknife-compiler:${butterknifeVersion}"
}
```

**LibBaseActivity.java**
```
public class LibBaseActivity extends AppCompatActivity {
    // another code...

    @Override
    public void setContentView(@LayoutRes int layoutResID) {
        super.setContentView(layoutResID);
        ButterKnife.bind(this);
    }
    
    // another code...
}
```

**TestingActivity.java**
```
public class TestingActivity extends LibBaseActivity {
    @BindView(R.id.tv_sample)
    TextView tvSample;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_directory);

        tvSample.setText("Hello World");
    }
}
```

LibraryTest Project Source
===

**MainActivity.java**
```
public class MainActivity extends AppCompatActivity implements View.OnClickListener {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Button btnTest = (Button) findViewById(R.id.btn_test);
        btnTest.setOnClickListener(this);
    }

    @Override
    public void onClick(View v) {
        startActivity(new Intent(this, TestingActivity.class));
    }
}
```

Logcat Error Logs
===
```
FATAL EXCEPTION: main
Process: xyz.dev_juyoung.libararytest, PID: 27961
java.lang.NoClassDefFoundError: Failed resolution of: Lbutterknife/ButterKnife;
	at xyz.dev_juyoung.picker.base.LibBaseActivity.setContentView(LibBaseActivity.java:32)
	at xyz.dev_juyoung.picker.activities.TestingActivity.onCreate(TestingActivity.java:13)
	at android.app.Activity.performCreate(Activity.java:6904)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
	at android.app.ActivityThread.access$1100(ActivityThread.java:229)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7406)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.ClassNotFoundException: Didn't find class "butterknife.ButterKnife" on path: DexPathList[[zip file "/data/app/xyz.dev_juyoung.librarytest-1/base.apk"],nativeDirectories=[/data/app/xyz.dev_juyoung.librarytest-1/lib/arm64, /vendor/lib64, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 14 more
	Suppressed: java.lang.ClassNotFoundException: butterknife.ButterKnife
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 15 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

```

**Comment by dj-4war** [comment]
Any update on this ? found the same issue on one device where as it is working on other devices.

**Comment by JakeWharton** [comment]
aars do not carry dependencies so the consuming project needs a butterknife dependency setup or you need to publish to a maven host where the transitive dependency can be reflected in a pom. There's no action for butter knife to take here.
