### ISSUE TITLE
 Build failed when update to 8.5.2-SNAPSHOT-2017-05-08: No such file or directory

### ISSUE THREAD

**Issue by xjh1994** [JakeWharton/butterknife#952]
```
Execution failed for task ':baselibrary:processReleaseResources'.
> /Users/xjh1994/AndroidStudioProjects/xxx/baselibrary/build/generated/source/r/release/com.xxx.xxx.baselibrary/R.java (No such file or directory)

```

**Comment by xjh1994** [comment]
R.java exists

**Comment by JakeWharton** [comment]
Why is this a ButterKnife issue?

**Comment by xjh1994** [comment]
@JakeWharton Well, as late as yesterday it worked well using 8.5.2-SNAPSHOT. And today after AS update ButterKnife dependencies.

Here are the details.

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':baselibrary:processReleaseResources'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.io.FileNotFoundException: /Users/xjh1994/AndroidStudioProjects/Prototype/baselibrary/build/generated/source/r/release/com.tianxiabuyi.prototype.baselibrary/R.java (No such file or directory)
        at com.github.javaparser.JavaParser.parse(JavaParser.java:156)
        at com.github.javaparser.JavaParser.parse(JavaParser.java:177)
        at butterknife.plugin.FinalRClassBuilder.brewJava(FinalRClassBuilder.java:36)
        at butterknife.plugin.ButterKnifePlugin$applyPlugin$1$1$1.execute(ButterKnifePlugin.kt:34)
        at butterknife.plugin.ButterKnifePlugin$applyPlugin$1$1$1.execute(ButterKnifePlugin.kt:15)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 20 more

```

**Comment by xjh1994** [comment]
I noticed that it was updated in May 8th

**Comment by xjh1994** [comment]
It uses a slash in the path inside instead of periods, such as 'generated/source/r/release/com.tianxiabuyi.prototype.baselibrary/R.java' which should be 'generated/source/r/release/com/tianxiabuyi/prototype/baselibrary/R.java'

I'm not sure if it's ButterKnife's problem, but I'll appreciate it if you can help me. Thanks!

**Comment by JakeWharton** [comment]
Got it. I'll look tomorrow.

**Comment by JakeWharton** [comment]
Typo on my part. Derp. PR incoming.

**Comment by xjh1994** [comment]
@JakeWharton Good job！ Thanks very much！BTW, We all want to have integration tests. That's why we can't use the SnapShot version in production. Ha-ha.

**Comment by JakeWharton** [comment]
I appreciate you checking the SNAPSHOT. I probably wouldn't have found that
bug until release.

**Comment by xjh1994** [comment]
@JakeWharton  I was having problems developing a multi module project, #779  and then I upgraded to SnapShot and found the problem. Well, have a good time!
